Terrain surface materials list component.
o3de/o3de.org pull request #1018
Opened 2021-10-07 13:21 UTC by sphrose

Signed-off-by: sphrose <82213493+sphrose@users.noreply.github.com>

2021-11-06 02:13 UTC, FiniteStateGit requested changes

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/terrain/surface_material_list.md
> +
```suggestion

## Dependencies

The [Axis Aligned Box Shape Component](/docs/user-guide/components/reference/shape/axis-aligned-box-shape) is required for the Terrain Surface Materials List component to operate.

```
Suggest adding a dependencies section to match the format of other component reference pages.

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/gems/reference/environment/terrain/_index.md
>  | [Terrain Layer Spawner](/docs/user-guide/components/reference/terrain/layer_spawner.md) | Spawns a terrain region contained within configurable bounds, and allows prioritization of overlapping terr
```suggestion
| [Terrain Layer Spawner](/docs/user-guide/components/reference/terrain/layer_spawner) | Spawns a terrain region contained within configurable bounds, and allows prioritization of overlapping terrain layers. |
```

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/gems/reference/environment/terrain/_index.md
> +| [Terrain Height Gradient List](/docs/user-guide/components/reference/terrain/height_gradient_list/) | Provides terrain height data from a list of gradients. |
```suggestion
| [Terrain Height Gradient List](/docs/user-guide/components/reference/terrain/height_gradient_list) | Provides terrain height data from a list of gradients. |
```

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/gems/reference/environment/terrain/_index.md
> +| [Terrain Surface Material List](/docs/user-guide/components/reference/terrain/surface_material_list/) | Defines mappings between a surface type and a render material. |
```suggestion
| [Terrain Surface Material List](/docs/user-guide/components/reference/terrain/surface_material_list) | Defines mappings between a surface type and a render material. |
```

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/_index.md
>  | [Terrain Layer Spawner](/docs/user-guide/components/reference/terrain/layer_spawner/) | Spawns a terrain region contained within configurable bounds, and allows prioritization of overlapping terrai
```suggestion
| [Terrain Layer Spawner](/docs/user-guide/components/reference/terrain/layer_spawner) | Spawns a terrain region contained within configurable bounds, and allows prioritization of overlapping terrain layers. |
```
Suggesting these url changes to align with edits in the Terrain Collider PR.

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/_index.md
> +| [Terrain Height Gradient List](./terrain/height_gradient_list/) | Provides terrain height data from a list of gradients. |
```suggestion
| [Terrain Height Gradient List](./terrain/height_gradient_list) | Provides terrain height data from a list of gradients. |
```

2021-11-06 02:13 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/_index.md
> +| [Terrain Surface Material List](./terrain/surface_material_list/) | Defines mappings between a surface type and a render material. |
```suggestion
| [Terrain Surface Material List](./terrain/surface_material_list) | Defines mappings between a surface type and a render material. |
```

2021-11-06 02:19 UTC, FiniteStateGit commented
I mentioned this in the Terrain Collider PR, but the filenames use underscores, I'm not sure if hyphens should be used.

2021-11-09 11:13 UTC, sphrose commented
> 
> 
> I mentioned this in the Terrain Collider PR, but the filenames use underscores, I'm not sure if hyphens should be used.

I've made this change just in case.

2021-11-09 16:26 UTC, FiniteStateGit approved these changes
Looks good, approved.

2021-11-12 00:50 UTC, sptramer commented
@sphrose Looks like there are conflicts - can you resolve them and I'll re-review tomorrow?

2021-11-12 08:17 UTC, sphrose commented
> 
> 
> @sphrose Looks like there are conflicts - can you resolve them and I'll re-review tomorrow?

Done

2021-11-12 22:12 UTC, sptramer approved these changes

2021-11-12 22:13 UTC, sptramer commented
@mbalfour-amzn Please merge after tech review. Thanks!

2021-11-15 21:45 UTC, mbalfour-amzn approved these changes

2021-11-15 21:52 UTC, merged