User Guide Assets Section Part 4.
o3de/o3de.org pull request #1086
Opened 2021-10-21 22:01 UTC by micronAMZN

Signed-off-by: Mike Cronin <mikecro@amazon.com>

## Change summary

This organizes all the Asset Processor specific topics into one section. Relies on images in PR# 1082.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2021-11-03 03:56 UTC, sptramer requested changes
One broken link, otherwise looks good!

2021-11-03 03:56 UTC, sptramer commented on content/docs/user-guide/assets/asset-processor/_index.md
> +| [Faster Scanning](faster-scannning) | Asset Processor's faster scanning mode uses source asset timestamps and quick source asset checks to determine if assets need to be processed. |
```suggestion
| [Faster Scanning](faster-scanning) | Asset Processor's faster scanning mode uses source asset timestamps and quick source asset checks to determine if assets need to be processed. |
```

Looks like there was a small typo in here.

2021-11-11 01:33 UTC, sptramer approved these changes

2021-11-12 23:27 UTC, carrcain requested changes
Editorial review.

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/interface.md
> +The Event Log Details table displays asset processing information for the asset selected the Asset Status table. This table provides an activity log that shows how the asset was processed and any err
```suggestion
The Event Log Details table displays asset processing information for the asset selected in the Asset Status table. This table provides an activity log that shows how the asset was processed and any errors or warnings generated during processing.

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/interface.md
> +| **Outgoing Product Dependencies** | The list of product assets which depend on this product asset. |
```suggestion
| **Outgoing Product Dependencies** | The list of product assets that depend on this product asset. |

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/interface.md
> +| **Outgoing Unmet Path Product Dependencies**<sup>1</sup> | The list of product assets which are hardcoded paths to be loaded by the O3DE runtime. |
```suggestion
| **Outgoing Unmet Path Product Dependencies**<sup>1</sup> | The list of product assets that are hardcoded paths to be loaded by the O3DE runtime. |

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/interface.md
> +| **Incoming Product Dependencies** | The list of product assets which this product asset depends on. |
```suggestion
| **Incoming Product Dependencies** | The list of product assets that this product asset depends on. |

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/interface.md
> +The Logs tab displays logs for Asset Processor itself, not for process jobs. If you are having issues with a specific process job, start debugging with the the logs for the job found in the Jobs tab.
```suggestion
The Logs tab displays logs for Asset Processor itself, not for process jobs. If you are having issues with a specific process job, start debugging with the logs for the job found in the Jobs tab. The type of errors displayed in the Logs tab are often related issues with managing the process jobs, maintaining the Asset Cache, and writing log information for process jobs. 

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/debugging.md
> +If you are having issues with **Asset Processor** use the methods below to debug the issues.
```suggestion
If you are having issues with **Asset Processor**, use the methods below to debug the issues.

```

2021-11-12 23:27 UTC, carrcain commented on content/docs/user-guide/assets/asset-processor/debugging.md
> +If Asset Processor isn't working as expected, use the information in the **Logs** tab to debug the issue. The Logs tab contains log information for Asset Processor and not for individual process jobs
Point to where they can find debug info for individual jobs.

2021-12-08 17:48 UTC, merged

2021-12-08 17:48 UTC, sptramer commented
Mike addressed comments from AWS editorial, who do not have the time to re-review right now, so merging under the auspices of "Mike accepted the copyedit."