image-width shortcode. This shortcode adds an image with a restricted…
o3de/o3de.org pull request #1117
Opened 2021-10-28 21:40 UTC by micronAMZN

… width and alt text. Need this for .svgs that scale up infinitely.

Signed-off-by: Mike Cronin <mikecro@amazon.com>

## Change summary

Adding a shortcode that will add an image with alt text that is restricted to a specified width. Need this to keep svgs from scaling to ridiculous sizes. Can be used to scale screenshots that are very large as well, though the final image quality will be affected by the browser.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2021-11-03 23:10 UTC, willihay requested changes

2021-11-03 23:10 UTC, willihay commented on content/docs/contributing/to-docs/style-guide/media.md
> +1. image name
```suggestion
1. image link
```

2021-11-03 23:10 UTC, willihay commented on content/docs/contributing/to-docs/style-guide/media.md
> +`image-width` takes three parameters in order:
```suggestion
`image-width` takes three double-quoted parameters in order:
```

2021-11-03 23:10 UTC, willihay commented on content/smoketest.md
> +`image-width` takes three parameters in order:
```suggestion
`image-width` takes three double-quoted parameters in order:
```

2021-11-03 23:10 UTC, willihay commented on content/smoketest.md
> +1. image name
```suggestion
1. image link
```

2021-11-04 16:20 UTC, chanmosq approved these changes
Minor, non-blocking suggestions.

2021-11-04 16:20 UTC, chanmosq commented on content/docs/contributing/to-docs/style-guide/media.md
> +Alternate text for images is very important. It provides a description of the image if the image is not loaded. The alternate text is also used in accessibility scenarios and in search engine optimiz
```suggestion
Alternate text for images is very important. It provides a description of the image if the image is not loaded. The alternate text is also used for accessibility and in search engine optimization (SEO). Ensure that the alternate text provided for images clearly describes the contents of the image. 
```

2021-11-04 23:24 UTC, willihay approved these changes

2021-11-04 23:25 UTC, merged