Website - Add Community Collaboration section to Homepage
o3de/o3de.org pull request #1189
Opened 2021-11-18 07:00 UTC by AMZN-daimini

Adding a Community Collaboration section to the homepage.

![collaboration](https://user-images.githubusercontent.com/82231674/142366706-28a66910-ec9b-49d5-a0d4-ed601b3d7460.gif)

2021-11-18 07:05 UTC, AMZN-daimini commented
Sorry for the base switching, had to update staging to display the correct diffs :)

2021-11-18 16:18 UTC, bhanuja-s requested changes
Brilliant, thank you for the GIF! A few comments:
- The button for the second card should be "View" as it would go to a new tab.
- We don't need the "View more projects" button for this release.
- There should be a 20% overlay (#000000) for the card, which should be 50% on the hover state.

2021-11-19 18:23 UTC, erickson-doug approved these changes

2021-11-19 18:23 UTC, merged

2021-11-19 18:25 UTC, AMZN-daimini commented
> Brilliant, thank you for the GIF! A few comments:
> 
> * The button for the second card should be "View" as it would go to a new tab.
> * We don't need the "View more projects" button for this release.
> * There should be a 20% overlay (#0) for the card, which should be 50% on the hover state.

Neat, I will apply these changes in a separate PR