Updated asset-types.
o3de/o3de.org pull request #1288
Opened 2021-12-09 17:42 UTC by micronAMZN

Moved new asset-types topic up a level to /assets. Added product assets to table. Added more asset types. Improved descriptions. Removed old asset-file-types topic. This table is not complete. We will continue to update as new asset types are discovered.

Signed-off-by: Mike Cronin <mikecro@amazon.com>

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2021-12-14 22:01 UTC, chanmosq approved these changes
Minor style suggestions

2021-12-14 22:01 UTC, chanmosq commented on content/docs/user-guide/assets/asset-types.md
> +| `.scriptcanvas` | A Script Canvas graph created with Script Canvas Editor, which is O3DE's visual scripting tool. | `.scriptcanvas_compiled`</br>`.scriptcanvas_fn_compiled`</br>`.luac` |
```suggestion
| `.scriptcanvas` | A Script Canvas graph created with **Script Canvas Editor**, which is O3DE's visual scripting tool. | `.scriptcanvas_compiled`</br>`.scriptcanvas_fn_compiled`</br>`.luac` |

```

2021-12-15 00:49 UTC, willihay requested changes

2021-12-15 00:49 UTC, willihay commented on content/docs/user-guide/assets/asset-types.md
> +| `.material` | Stores the properties and values, including texture assignments, that define the look of a surface for rendering. | `.azmaterial` |
The alphabetized order is interrupted starting with `.material` appearing after `.stl`. Can you help those of us who are bothered by this and fix the alphabetization? :P

2021-12-15 00:49 UTC, willihay commented on content/docs/user-guide/assets/asset-types.md
> +
Blank line breaks the table rendering.
```suggestion
```

2021-12-15 17:22 UTC, willihay approved these changes
It's still out of alphabetical order towards the end of the table, but I don't feel like it's worth pressing for another round of changes.

2021-12-15 19:21 UTC, willihay commented
Yay! Happy now. :-)

2021-12-15 19:22 UTC, merged