Adding tutorial page for Pong videos
o3de/o3de.org pull request #1291
Opened 2021-12-09 21:16 UTC by erickson-doug

Signed-off-by: Doug Erickson <dougeric@amazon.com>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2021-12-09 22:20 UTC, willihay requested changes

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/_index.md
> +| [Create your first O3DE game: Pong](first-project/) | Start from a new O3DE project and build your first game: Pong! What's "Pong"? Two paddles square off, in a ball-based battle to land the highes
```suggestion
| [Create your first O3DE game: Pong](tutorials/first-project/) | Start from a new O3DE project and build your first game: Pong! What's "Pong"? Two paddles square off, in a ball-based battle to land the highest score. This tutorial series will introduce you to basic game UI development, scripting, and controls in O3DE. |
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +linkTitle: PostFX
copy-paste lolz
```suggestion
linkTitle: Pong Game
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +menu_uuid: Your First Project
This metadata is not needed:
```suggestion
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +## Video Tutorial Series: Create the Pong Game with Open 3D Engine (O3DE)
You've already introduced the abbreviation in the intro paragraph.
```suggestion
## Video Tutorial Series: Create the Pong Game with O3DE
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +This topic contains video tutorials that will guide you through creating a Pong game in Open 3D Engine (O3DE), from creating a new project to defining gameplay state and user interface elements.
Latest style we've been using:
```suggestion
This topic contains video tutorials that will guide you through creating a Pong game in **Open 3D Engine (O3DE)**, from creating a new project to defining gameplay state and user interface elements.
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +Games, as conventional wisdom goes, started with Pong. Your experience with O3DE can start with Pong, too! Let AWS GameTech's technical trainer, Alex Damarjian, guide you through learning the basics
Unlike GameLift, they spell it "Game Tech", with a space.
```suggestion
Games, as conventional wisdom goes, started with Pong. Your experience with O3DE can start with Pong, too! Let AWS Game Tech's technical trainer, Alex Damarjian, guide you through learning the basics of O3DE game development with this series, while letting you relive history with a modern game engine and tools.  
```

2021-12-09 22:20 UTC, willihay commented on content/docs/learning-guide/tutorials/first-project/_index.md
> +[Take me to the full playlist!](https://www.youtube.com/watch?v=kK0XnYFKw38&list=PLCQwFpnHSZQhhsr6iJqyeYqKe6dexnHh9)
Technically, your link takes you to the first video in the series, not the playlist. Here's the playlist link:
```suggestion
[Take me to the full playlist!](https://www.youtube.com/playlist?list=PLCQwFpnHSZQhhsr6iJqyeYqKe6dexnHh9)
```

2021-12-09 22:20 UTC, willihay commented on content/docs/welcome-guide/_index.md
> +| [Create your first game: Pong!](/tutorials/first-project/)
```suggestion
| [Create your first game: Pong](/docs/learning-guide/tutorials/first-project/) | Start from a new O3DE project and build your first game: Pong! What's "Pong"? Two paddles square off, in a ball-based battle to land the highest score. This tutorial series will introduce you to basic game UI development, scripting, and controls in O3DE. |
```

2021-12-10 00:02 UTC, willihay approved these changes

2021-12-10 04:34 UTC, adamarjian1 approved these changes

2021-12-10 16:34 UTC, merged