Code gems
o3de/o3de.org pull request #1299
Opened 2021-12-10 22:43 UTC by chanmosq

## Change summary

In the `user-guide/gems/` section:
- Improve discoverability of Gem development documentation, which is located in `user-guide/programming/gems`. 
- Improve discoverability of common workflows with Gems: 1) Adding Gems to projects and 2) Developing code Gems
- Defined Gem terminology used throughout docs: standard O3DE Gems, third party Gems, custom Gems.

In the `user-guide/programming/gems` section: 
- Added a topic that describes the code components in a Gem. 

### Submission Checklist:

* [X] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [X] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [X] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [X] **Help the user** - Does the documentation show the user something *meaningful*?

2021-12-16 21:58 UTC, willihay requested changes

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/gems/_index.md
> +Gems come from the different sources:
```suggestion
Gems come from three different sources:
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/gems/_index.md
> +1. Register the Gem, if it's not already. O3DE already registers Gems its bundled with. However, you must register Gems from an external source. Refer to [Register Gems to a Project](/docs/user-guide
```suggestion
1. Register the Gem, if it's not already. Standard Gems that are bundled with O3DE are already registered. However, you must register Gems from an external source. Refer to [Register Gems to a Project](/docs/user-guide/project-config/register-gems/).
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/programming/gems/code-gems.md
> +linktitle: Create an O3DE Code Gem
Old title?
```suggestion
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/programming/gems/code-gems.md
> +weight: 200
Move this topic after "Create an O3DE Gem" to match the topic list.
```suggestion
weight: 300
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/programming/gems/code-gems.md
> +## Gem Code
```suggestion
## Gem code
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/programming/gems/manifest.md
>  weight: 200
```suggestion
weight: 400
```

2021-12-16 21:58 UTC, willihay commented on content/docs/user-guide/programming/gems/overview.md
> +title: Gem Module system in Open 3D System
I think you meant this?
```suggestion
title: Gem Module System in Open 3D Engine
```

2022-01-03 18:37 UTC, chanmosq commented
@willihay 
You don't have to review the new `overview.md` files, they have content that already existed. In the last commit, I set up the docs so that the left-hand navigation shows:
- Gems (dropdown)
  - Overview

Previously it showed: 
- Gems (dropdown)
  - Gems

I did this by moving the contents in the `_index.md` file into an `overview.md` file. Note that `_index.md` still exists as it helps define the Gems section in the file hierarchy.

2022-01-05 21:08 UTC, micronAMZN approved these changes
Approving with a couple of suggestions.

2022-01-05 21:08 UTC, micronAMZN commented on content/docs/user-guide/programming/gems/code-gems.md
> +The `<Gem>SystemComponent` class is a global singleton class that's responsible for managing the Gem's code. The system components allows the component within the Gem Module to communicate with compo
This is a lot of info in a short passage. Suggestion to make it easier to digest, maybe?

```suggestion
The `<Gem>SystemComponent` class is a global singleton class that's responsible for managing the Gem's code. The Gem Module registers the Gem System Component which manages the Gem Module's life cycle: initialization, activation, and deactivation. The Gem System Component activates when the Gem loads and deactivates when the Gem unloads.

The Gem System Component allows the component within the Gem Module to communicate with components from other Gems by connecting to their EBus. It also handles initialization and shutdown, events, memory allocation, and debugger connections. 
```

2022-01-10 19:00 UTC, chanmosq commented on content/docs/user-guide/programming/gems/code-gems.md
> +**Open 3D Engine (O3DE)** code Gems contains code that let's you extend the O3DE Editor or integrate features and gameplay logic for your project. They can also contain assets that your code interact
Done, and thanks for the additional use case!

2022-01-12 22:27 UTC, willihay approved these changes

2022-01-12 22:27 UTC, merged