Fix broken links to /asset-processor/
o3de/o3de.org pull request #1324
Opened 2021-12-23 21:06 UTC by FiniteStateGit

- Fixes a few dead links to /user-guide/assets/asset-processor/.

Fix #1224

2022-01-03 20:34 UTC, micronAMZN approved these changes

2022-01-03 20:39 UTC, micronAMZN requested changes
Minor style fixes as well.

2022-01-03 20:39 UTC, micronAMZN commented on content/docs/user-guide/build/reference.md
> +* **`LY_ASSET_DEPLOY_TYPE`** - The *default* type of assets to be built by the [asset processor](/docs/user-guide/assets/asset-processor/). Valid platforms are:
```suggestion
* **`LY_ASSET_DEPLOY_TYPE`** - The *default* type of assets to be built by [Asset Processor](/docs/user-guide/assets/asset-processor/). Valid platforms are:
```

2022-01-03 20:39 UTC, micronAMZN commented on content/docs/user-guide/packaging/asset-bundler/list-operations.md
> +1. Process the assets on your project by running the [Asset Processor](/docs/user-guide/assets/asset-processor/).
```suggestion
1. Process the assets on your project by running [Asset Processor](/docs/user-guide/assets/asset-processor/).
```

2022-01-03 20:39 UTC, micronAMZN commented on content/docs/user-guide/packaging/asset-bundler/overview.md
> ++ The assets that you are bundling have been processed by the [Asset Processor](/docs/user-guide/assets/asset-processor/).
```suggestion
+ The assets that you are bundling have been processed by [Asset Processor](/docs/user-guide/assets/asset-processor/).
```

2022-01-04 16:38 UTC, micronAMZN approved these changes

2022-01-04 21:41 UTC, AMZN-alexpete approved these changes

2022-01-06 18:50 UTC, merged