Revised "Contributor Guide" (style, formatting, and file structure)
o3de/o3de.org pull request #1411
Opened 2022-02-08 22:59 UTC by chanmosq

- Moved content of `_index.md` to `overview.md`. (There were no changes in the content). The purpose of this change is so the first page of the section is called "Overview", instead of having the same title as the section title. 
- Shortened all instances of "Open 3D Engine" in page titles to "O3DE" and made sure all pages mentioned "**Open 3D Engine (O3DE)**" in the first paragraph. The purpose of this change is to make long page titles more concise, and apply that change so its consistent with other pages. 
- Other minor style and formatting revisions.

Signed-off-by: Chanelle Mosquera <75444793+chanmosq@users.noreply.github.com>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-02-14 17:26 UTC, FiniteStateGit requested changes
I think that the first two links on the table in `/docs/contributing/_index.md`, could point to `/to-docs/overview` and `/to-code/overview`.

2022-02-14 17:26 UTC, FiniteStateGit commented on content/docs/contributing/to-docs/hugo.md
>  description: Learn to work with Hugo, the static site generator for O3DE documentation
```suggestion
description: Learn to work with Hugo, the static site generator for O3DE documentation.
```

2022-02-14 22:06 UTC, chanmosq commented
> I think that the first two links on the table in `/docs/contributing/_index.md` could point to `/to-docs/overview` and `/to-code/overview`.

The table of contents (Section / Description) table in the [Contributing](https://www.o3de.org/docs/contributing/) landing page? They currently point to the **To Code** and **To Docs** sections. Not sure where you mean?

2022-02-14 23:17 UTC, FiniteStateGit approved these changes

2022-02-20 20:24 UTC, sptramer approved these changes
Approved pending the (easy-looking) merge conflict. @chanmosq address that and I can merge.

2022-02-21 22:41 UTC, chanmosq commented
@sptramer Resolved merge conflicts!

2022-02-21 22:46 UTC, sptramer approved these changes

2022-02-21 22:47 UTC, merged