Added Chromatic Aberration Doc
o3de/o3de.org pull request #1433
Opened 2022-02-21 09:40 UTC by tjmgd

Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-02-23 17:53 UTC, sptramer commented
Blocked by https://github.com/o3de/o3de/pull/7640

2022-03-02 20:45 UTC, micronAMZN requested changes
Thanks for your contribution!

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +The **Chromatic Aberration** component creates *Chromatic Aberration*, a post-processing effect that simulates the failure of a lens to focus all colors to the same point.
Using the word failure here might suggest this a a bad thing to users who aren't familiar with this concept, as opposed to a visual effect that is sometimes desired.

```suggestion
The **Chromatic Aberration** component is a post-processing effect that simulates a lens that focuses different wavelengths of light at different points, creating fringes of color around edges in the image.
```

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +
Removing some whitespace
```suggestion
```

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +
Removing some whitespace
```suggestion
```

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +
Removing some whitespace
```suggestion
```

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +
Need interface image here.

2022-03-02 20:45 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/chromatic-aberration.md
> +| **Blend** | Scales the blending of the effect with the original image, i.e. reduces sharpness. | Float: 0.0 - 1.0 | `0.5` |
Suggest avoiding Latin and abbreviations per the style guide.

```suggestion
| **Blend** | Scales the blending of the effect with the original image which reduces the sharpness of the effect. | Float: 0.0 - 1.0 | `0.5` |
```

2022-03-03 20:12 UTC, FiniteStateGit reviewed
Thanks for the contribution.

Would it be possible to add a representative screenshot of the effect?  I think something similar to your screenshot of the exaggerated effect would work well, even better if you could isolate the effect from background noise like the grid and hdri map.

![chromatic-aberation](https://user-images.githubusercontent.com/31811688/156644292-a7719888-a16c-489f-9f73-45c0388901be.png)

2022-03-18 18:49 UTC, rgba16f commented
@tjmgd any update?

2022-03-25 16:38 UTC, micronAMZN commented
Moved to development branch, because https://github.com/o3de/o3de/pull/7640 is submitted to development.

2022-07-25 11:31 UTC, tjmgd commented
I seem to have made a mess of a rebase! I will repair this first.

2022-07-27 15:50 UTC, FiniteStateGit commented
@tjmgd I think the Bloom component page was added to the PR instead of Chromatic Aberration when you rebased.

2022-08-31 21:09 UTC, FiniteStateGit commented
Thank you for the contribution @tjmgd! Closing this in favor of https://github.com/o3de/o3de.org/pull/1949.

2022-08-31 21:09 UTC, closed without merging