Texture Settings tool documentation
o3de/o3de.org pull request #1459
Opened 2022-03-03 16:59 UTC by micronAMZN

New documentation on the Texture Settings tool and information about image file formats supported by O3DE. This PR relies on the following PRS submitted to O3DE:

https://github.com/o3de/o3de/pull/7729
https://github.com/o3de/o3de/pull/7475

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-03-25 16:50 UTC, micronAMZN commented on content/docs/user-guide/assets/texture-settings/_index.md
> +
Thanks for this, however, If I had to estimate, more often than not users will want to use this tool even if they specify a preset with a naming convention. I'll revisit this and see how I can incorporate the spirit of your suggestion.

2022-03-25 16:52 UTC, micronAMZN commented on content/docs/user-guide/assets/texture-settings/interface.md
> +### Texture presets
will do.

2022-03-25 16:54 UTC, micronAMZN commented on content/docs/user-guide/assets/texture-settings/interface.md
> +| Opacity | A linear grayscale image containing opacity values. | A grayscale image with one channel. | Desktop: BC4<br>Mobile: ASTC_4x4 | `_blend`<br>`_mask`<br>`_msk`<br>`_o`<br>`_op`<br>`_opac`<br
Had intended to use grayscale because that's US English, however greyscale as you noted is used in the source and interface.

2022-03-29 22:20 UTC, willihay requested changes

2022-03-29 22:20 UTC, willihay commented on content/docs/user-guide/assets/texture-settings/texture-assets.md
> +* A 360 degree horizontal by 180 degree vertical projection of an environment.
```suggestion
* A 360-degree horizontal by 180-degree vertical projection of an environment.
```

2022-03-30 14:54 UTC, micronAMZN commented on content/docs/user-guide/assets/texture-settings/texture-presets.md
> +| UserInterface Lossless | An uncompressed linear color texture that contains a UI element with an 8-bit alpha channel. | An RGBA image. | R8G8B8A8 | `_ui` |
Nice catch.

2022-03-30 18:05 UTC, willihay approved these changes
Nice addition!

2022-03-30 21:17 UTC, paucom reviewed
Starting editorial review now...

2022-04-04 17:53 UTC, chanmosq approved these changes

2022-05-03 22:38 UTC, micronAMZN commented
Closing in favor of #1598

2022-05-03 22:38 UTC, closed without merging