Exposure Control component reference doc
o3de/o3de.org pull request #1478
Opened 2022-03-10 00:50 UTC by chanmosq

## Change summary

Author document for the Exposure Control component reference. 

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

2022-03-15 22:24 UTC, sptramer approved these changes

2022-03-16 23:45 UTC, FiniteStateGit requested changes

2022-03-16 23:45 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/exposure-control.md
> +| **Minimum Exposure** | The minimum exposure value at which automatic exposure can automatically adjust to. | Float: -16.0 - 16.0 | `-16.0` |
```suggestion
| **Minimum Exposure** | The minimum value that the exposure automatically adjusts to. | Float: -16.0 - 16.0 | `-16.0` |
```

2022-03-16 23:45 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/exposure-control.md
> +| **Maximum Exposure** | The maximum exposure value at which automatic exposure can automatically adjust to. | Float: -16.0 - 16.0 | `16.0` |
```suggestion
| **Maximum Exposure** | The maximum value that the exposure automatically adjusts to. | Float: -16.0 - 16.0 | `16.0` |
```

2022-03-16 23:45 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/exposure-control.md
> +| **Enable Heatmap** | Provides a histogram of the exposure values that the camera captures in the scene. It appears on top of the **Viewport**. You can move the camera to see the heatmap of other ar
```suggestion
| **Enable Heatmap** | Displays a histogram of the exposure values that the camera captures in the scene. It appears on top of the **Viewport**. You can move the camera to see the heatmap of other areas. Areas below the **Minimum Exposure** value are highlighted in blue, and areas above the **Maximum Exposure** value in red. The numbers on the heatmap represent exposure value stops. | None | `Disabled` |
```

2022-03-16 23:45 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/exposure-control.md
> +The **Exposure Control** component adjusts the amount of light the camera exposes in the scene, which controls how bright the scene appears. You can set the exposure manually, or use *Eye Adaptation*
```suggestion
The **Exposure Control** component adjusts the amount of light from the scene that the camera receives, which controls how bright the scene appears. You can set the exposure manually, or use *Eye Adaptation* mode to automatically adjust camera exposure based on the scene's brightness. Eye Adaptation mode adjusts the scene to a neutral middle gray lightness. You can make further adjustments to the automatic exposure by increasing or decreasing the **Manual Compensation** property.
```

2022-03-17 21:17 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/exposure-control.md
> +| **Overrides - Enabled Override** | If enabled, you can override Exposure Control settings to have advanced PostFX looks and control. | Boolean | `Enabled` |
Revised this part differently from your suggestion for more accuracy: 

>If enabled, you can override Exposure Control settings to have more control over how the PostFX behaves and looks.

2022-03-17 21:40 UTC, FiniteStateGit approved these changes

2022-03-17 21:42 UTC, merged