Author deferred fog component reference page. @netlify /docs/user-gui…
o3de/o3de.org pull request #1534
Opened 2022-04-11 23:33 UTC by chanmosq

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-04-12 14:48 UTC, galibzon approved these changes

2022-04-12 15:39 UTC, hershey5045 approved these changes

2022-04-14 17:36 UTC, FiniteStateGit requested changes
Minor suggestions, feel free to disregard what you don't like!

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +Cloud turbulence is implemented by ray marching along the fog layer and combining two moving noise octaves, creating a "cloudy" fog look. You can configure each octave by scaling the UV coordinates o
```suggestion
Cloud turbulence is implemented by ray marching along the fog layer and combining two moving noise octaves, creating a "cloudy" fog look. You can configure each octave by scaling the UV coordinates of the noise texture and defining the velocity of the texture's movement. You can also specify the amount of blend between the two octaves.
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Fog Color** | The color of the fog that gradually blends with the scene. Becomes more opaque as the fog blends towards the **Fog End Distance**.  | Color | R: `115`, G: `115`, B: `153` |
```suggestion
| **Fog Color** | The color of the fog that gradually blends with the scene. The color becomes more opaque as the fog blends towards the **Fog End Distance**.  | Color | R: `115`, G: `115`, B: `153` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Fog Start Distance** | The distance from the viewer, measured in meter units, at which the fog starts. At this point, the fog begins to gradually blend with the scene until it completely masks th
```suggestion
| **Fog Start Distance** | The distance from the viewer, measured in meters, at which the fog starts. At this distance, the fog begins to gradually blend with the scene until it completely masks the background scene at the **Fog End Distance**. | Float: 0.0 - 5000.0 | `1.0` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Fog End Distance** | The distance from the viewer, measured in meter units, at which the fog completely masks out the background scene. From the **Fog Start Distance** to the **Fog End Distance**
```suggestion
| **Fog End Distance** | The distance from the viewer, measured in meters, at which the fog completely masks out the background scene. From the **Fog Start Distance** to the **Fog End Distance**, the fog blends with the scene, creating a gradual transition between the scene and the masked layer of fog. At and beyond this distance, the scene appears a solid color, completely masked by the fog layer.  | Float: 0.0 - 5000.0 | `5.0` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Fog Bottom Height** | The height of the bottom of the fog layer, measured in meter units, when **Enable Fog Layer** is activated. | Float: -5000.0 - 5000.0 | `0.01` |
```suggestion
| **Fog Bottom Height** | The height of the bottom of the fog layer, measured in meters, when **Enable Fog Layer** is activated. | Float: -5000.0 - 5000.0 | `0.01` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Fog Max Height** | The height of the top of fog layer, measured in meter units, when **Enable Fog Layer** is activated. | Float: -5000.0 - 5000.0 | `1.0` |
```suggestion
| **Fog Max Height** | The height of the top of the fog layer, measured in meters, when **Enable Fog Layer** is activated. | Float: -5000.0 - 5000.0 | `1.0` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Noise Texture First Octave Velocity** | The velocity of the noise texture's movement for the first octave, measured in meter units. | Vector2: -Infinity to Infinity | X: `0.002`, Y:`0.0032` |
```suggestion
| **Noise Texture First Octave Velocity** | The velocity of the noise texture's movement for the first octave, measured in meters per second. | Vector2: -Infinity to Infinity | X: `0.002`, Y:`0.0032` |
```

2022-04-14 17:36 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/deferred-fog.md
> +| **Noise Texture Second Octave Velocity** | The velocity of the noise texture's movement for the second octave, measured in meter units. | Vector2: -Infinity to Infinity | X: `0.00275`, Y: `-0.004`
```suggestion
| **Noise Texture Second Octave Velocity** | The velocity of the noise texture's movement for the second octave, measured in meters per second. | Vector2: -Infinity to Infinity | X: `0.00275`, Y: `-0.004` |
```

2022-04-21 16:30 UTC, Adi-Amazon approved these changes
Thanks for adding this documentation.
Perhaps important to add that currently the fog does not interacts with lighting, something that can be next future feature to add and will give the final touch towards being visualized as volumetric fog.

2022-04-26 19:41 UTC, chanmosq commented
> Thanks for adding this documentation. Perhaps important to add that currently the fog does not interacts with lighting, something that can be next future feature to add and will give the final touch towards being visualized as volumetric fog.

Added! Thank you for the additional information.

2022-04-26 19:44 UTC, Adi-Amazon approved these changes

2022-04-29 16:26 UTC, chanmosq commented
Hey @FiniteStateGit, when you get the chance can you review the changes I made per your suggestions? Thanks!

2022-05-06 22:01 UTC, FiniteStateGit approved these changes
Looks good!

2022-05-06 22:01 UTC, merged