Fixed poster link and upsdated poster image name to match the video.
o3de/o3de.org pull request #1566
Opened 2022-04-18 15:25 UTC by micronAMZN

Signed-off-by: Mike Cronin <58789750+micronAMZN@users.noreply.github.com>

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-04-18 15:56 UTC, sptramer commented
Looks like a build failure due to an inability in Hugo to mix-and-match positional and keyword:

```
8:26:22 AM: $ make preview-build
8:26:22 AM: hugo \
8:26:22 AM: 	--baseURL https://deploy-preview-1566--o3deorg.netlify.app/ \
8:26:22 AM: 	--buildDrafts \
8:26:22 AM: 	--buildFuture \
8:26:22 AM: 	--minify \
8:26:22 AM: 	--disableKinds="robotsTXT"
8:26:22 AM: Start building sites …
8:26:26 AM: Total in 3279 ms
8:26:26 AM: Error: Error building site: "/opt/build/repo/content/docs/contributing/to-docs/style-guide/media.md:194:185": got quoted positional parameter. Cannot mix named and positional parameters
8:26:26 AM: Makefile:15: recipe for target 'preview-build' failed
8:26:26 AM: make: *** [preview-build] Error 255
```

2022-04-18 15:57 UTC, sptramer requested changes

2022-04-18 15:57 UTC, sptramer commented on content/docs/contributing/to-docs/style-guide/media.md
> +    {{< video src="/images/contributing/to-docs/TestVideo.mp4" info="This is a test video." autoplay="true" loop="true" width="250" poster="/images/contributing/to-docs/TestPoster.png"" >}}
```suggestion
    {{< video src="/images/contributing/to-docs/TestVideo.mp4" info="This is a test video." autoplay="true" loop="true" width="250" poster="/images/contributing/to-docs/TestPoster.png" >}}
```

Looks like a typo that maybe led to the error?

2022-04-18 18:54 UTC, FiniteStateGit approved these changes

2022-04-21 18:37 UTC, sptramer approved these changes

2022-04-21 18:37 UTC, merged