Initial documentation and images for the material component
o3de/o3de.org pull request #1639
Opened 2022-05-13 06:32 UTC by gadams3

Signed-off-by: Guthrie Adams <guthadam@amazon.com>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-05-13 19:01 UTC, galibzon commented on content/docs/user-guide/components/reference/atom/material.md
> +The **Material** component is used to inspect, customize, and otherwise override materials and their properties on entities with compatible renderable components. [Mesh Component](/docs/user-guide/co
The Actor component link is broken.

2022-05-16 16:02 UTC, galibzon approved these changes

2022-05-19 02:22 UTC, chanmosq requested changes
Started review - clarified some sentences and left a few questions

2022-05-19 03:55 UTC, gadams3 commented on content/docs/user-guide/components/reference/atom/material.md
> +| The context menus and large button at the top of the Material Component give access to the 'Generate/Manage Source Materials' dialog. The dialog displays a list of the unique materials associated w
It initializes with default filenames based on the material slot name. Users can optionally select their own file names. We may replace this workflow with one that just selects a folder for all of the materials.

Which workflow? If the materials were previously exported from this dialog and customized in the material editor then they can be applied to any other entity. If multiple entities are selected when this dialog is opened from the component context menu, and they all share the same set of material slots, the generated materials will be assigned on every entity.

2022-05-19 18:23 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +The **Material** component is used to inspect, customize, and otherwise override materials and their properties on entities with compatible renderable components. [Mesh Component](/docs/user-guide/co
Ah yes that's key, my latest suggestion will address that.

2022-05-19 18:24 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +Use the **Material** component to inspect, customize, and override materials and properties used by other compatible components. Currently, only the [Mesh component](/docs/user-guide/components/refer
```suggestion
Use the **Material** component to inspect, customize, and override materials and properties on entities with compatible render components. Currently, only the [Mesh component](/docs/user-guide/components/reference/atom/mesh/) and the [Actor component](/docs/user-guide/components/reference/animation/actor/) support the Material component. However, any component can support the Material component by implementing the required buses and services. The Material component uses material assets, which you can create and configure using the Material Editor. Another way that material assets are produced is by the Asset Processor and the Model Asset Builder. This exports the materials defined within a source model, like an FBX file.
```

2022-05-19 18:27 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| The context menus and large button at the top of the Material Component give access to the 'Generate/Manage Source Materials' dialog. The dialog displays a list of the unique materials associated w
That answers it perfectly, thanks!

2022-05-19 22:03 UTC, chanmosq requested changes
Mentioned this in another comment, but I think an important concept we need to grasp when using the many material editing tools is what the difference is between "source material" and "material instances". There's some small hints to it, but it's not concretely defined or introduced. Getting crisp and being consistent with the terminology is important to lay the foundational understanding of materials in O3DE. 

(Note: "Material Instance" is defined in the [Atom Glossary](https://www.o3de.org/docs/atom-guide/glossary/), if you want to pull from that.)

2022-05-19 22:26 UTC, chanmosq requested changes

2022-05-19 22:26 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| **Generate/Manage Source Materials...** | This button opens the "Generate/Manage Source Materials" dialog. | | |
```suggestion
| **Generate/Manage Source Materials...** | This button opens the **Generate/Manage Source Materials** dialog. | | |
```

2022-05-19 22:26 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| **Default Material** | Materials assigned to the default material slot will be applied to the entire model wherever no higher priority model or LOD material is assigned. | Material Asset | None |
```suggestion
| **Default Material** | The default material applies to the entire model, except for parts where a higher priority model or LOD material is assigned. | Material Asset | None |
```

2022-05-19 22:26 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| **Model Materials** | Materials assigned to these slots will be applied to every part of the model with the same material slot name unless a higher priority LOD material is assigned. | Container of
```suggestion
| **Model Materials** | Materials that are assigned to these slots are applied to every part of the model with the same material slot name, unless a higher priority LOD material is assigned. | Container of material assets | Empty |
```

2022-05-19 22:26 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| **LOD Materials** | Materials assigned to LOD material slots will override model and default material assignments for the given LOD. If you are changing the default material or model materials and
```suggestion
| **LOD Materials** | Materials assigned to LOD material slots override **Default Material** and **Model Material** assignments for the given LOD. If you change the default material or model materials and don't see those changes applied, then verify that there's no LOD material taking higher priority or disable them completely. | Container of material assets organized by LOD | Empty |
```

2022-05-19 22:26 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +This request bus supplies the interface for interacting with the Material Component. Many of the functions relate to inspecting or customizing material asset and property overrides. All of the functi
```suggestion
This request bus supplies the interface for interacting with the Material component. It contains many of the functions that relate to inspecting or customizing material asset and property overrides. All of the functions are available in the editor, gameplay, and simulation. Many of them may be more useful for extending Material component related tools and scripts. 
```

2022-05-19 22:28 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/material.md
> +| 'GetOriginalMaterialAssignments' | Returns a map of available material slots and their default assignments | None | Unmodified Material Slot Layout: MaterialAssignmentMap | Yes |
```suggestion
| 'GetOriginalMaterialAssignments' | Returns a map of available material slots and their default assignments. | None | Unmodified Material Slot Layout: MaterialAssignmentMap | Yes |
```

Missing a period here and other method descriptions.

2022-05-20 03:34 UTC, gadams3 commented
> Mentioned this in another comment, but I think an important concept we need to grasp when using the many material editing tools is what the difference is between "source material" and "material instances". There's some small hints to it, but it's not concretely defined or introduced. Getting crisp and being consistent with the terminology is important to lay the foundational understanding of materials in O3DE.
> 
> (Note: "Material Instance" is defined in the [Atom Glossary](https://www.o3de.org/docs/atom-guide/glossary/), if you want to pull from that.)

is there a way to just link to that?

2022-05-20 16:55 UTC, chanmosq commented
> > Mentioned this in another comment, but I think an important concept we need to grasp when using the many material editing tools is what the difference is between "source material" and "material instances". There's some small hints to it, but it's not concretely defined or introduced. Getting crisp and being consistent with the terminology is important to lay the foundational understanding of materials in O3DE.
> > (Note: "Material Instance" is defined in the [Atom Glossary](https://www.o3de.org/docs/atom-guide/glossary/), if you want to pull from that.)
> 
> is there a way to just link to that?

The glossary definition of Material Instance is only part of the equation. I think the concept that's missing is the fact there is a distinction between the two, and their definition. To understand the material features, we also need to understand the terminology used. Would you be able to provide a definition for source material and add it to the glossary?

2022-05-20 17:50 UTC, gadams3 commented
> > > Mentioned this in another comment, but I think an important concept we need to grasp when using the many material editing tools is what the difference is between "source material" and "material instances". There's some small hints to it, but it's not concretely defined or introduced. Getting crisp and being consistent with the terminology is important to lay the foundational understanding of materials in O3DE.
> > > (Note: "Material Instance" is defined in the [Atom Glossary](https://www.o3de.org/docs/atom-guide/glossary/), if you want to pull from that.)
> > 
> > 
> > is there a way to just link to that?
> 
> The glossary definition of Material Instance is only part of the equation. I think the concept that's missing is the fact there is a distinction between the two, and their definition. To understand the material features, we also need to understand the terminology used. Would you be able to provide a definition for source material and add it to the glossary?

Source material is just the .material JSON file that can be opened in the material editor. We just started calling it that as an abbreviation for “.material source file”. That's also to distinguish them from “.azmaterial product asset”, the files output from the asset processor that show up in the asset browser. All assets have source files, the files fed into the asset processor, and product assets, the files output from the asset processor. Source and product assets should be documented in the asset system. 

The generate/manage materials dialog might need to be renamed. It does the opposite job of the asset processor. It converts product .azmaterial assets, that were produced using a different source file type, like FBX files, into .material source files that might not have existed.

Material instances are the active materials applied to models, as described. In the context of the material component, there is one material instance for each material slot. the material instance will be created based on which asset is being used. If the material component slot has custom properties for that instance then it must create a unique instance to apply those properties. if there are no unique properties set, it will share a material instance with anything else using the same material.

2022-05-20 21:43 UTC, chanmosq approved these changes

2022-05-20 21:55 UTC, merged