Grid component docs
o3de/o3de.org pull request #1641
Opened 2022-05-13 20:05 UTC by gadams3

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-05-13 20:24 UTC, chanmosq commented
@gadams3 Looks like Git pulled all the changes from main but registered them as your own commits. You'll need to fix this before review - so instead it will just show your 1 commit and 2 file changes. One way would be to start a fresh branch and cherry-pick your commits for Grid Component docs, and then force push to this original branch.

2022-05-13 22:25 UTC, FiniteStateGit requested changes
Minor suggestions and edits, thanks for submitting!

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +description: 'Open 3D Engine (O3DE) Grid Component reference.'
```suggestion
description: 'Open 3D Engine (O3DE) Grid component reference.'
```
The description metatag uses sentence casing.

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +The **Grid** component renders a wireframe grid. It is primarily used in tools to set a frame of reference and visualize relative sizes and distance between objects.
```suggestion
The **Grid** component renders a wireframe grid. It is primarily used in scene-building workflows to set a frame of reference and visualize relative sizes and distances between objects.
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +The component has a simple configuration for changing its size and appearance.
```suggestion
The Grid component has simple properties for changing its size and appearance.
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Grid Size** | The total grid size in meters. | Float | 32.0 |
```suggestion
| **Grid Size** | The total grid size in meters. | 0.0 - 1,000,000 | 32.0 |
```
The values column lists the range of acceptable values of a parameter.

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Axis Color** | The color used for drawing grid lines for the main axis. | Color | 0.0, 0.0, 1.0, 1.0 |
```suggestion
| **Axis Color** | The color used for drawing grid lines for the main axis. | (0-255, 0-255, 0-255) | (0, 0, 255) |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Primary Grid Spacing** | The distance between grid lines drawn in the primary color. | Float | 1.0 |
```suggestion
| **Primary Grid Spacing** | The distance between grid lines drawn in the primary color. | 0.1 to Infinity | 1.0 |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Primary Color** | The color used for drawing primary grid lines. | Color | 0.25, 0.25, 0.25, 1.0 |
```suggestion
| **Primary Color** | The color used for drawing primary grid lines. | (0-255, 0-255, 0-255) | (64, 64, 64) |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Secondary Grid Spacing** | The distance between grid lines drawn in the secondary color. | Float | 0.25 |
```suggestion
| **Secondary Grid Spacing** | The distance between grid lines drawn in the secondary color. | 0.1 to Infinity | 0.25 |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| **Secondary Color** | The color used for drawing secondary grid lines. | Color | 0.5, 0.5, 0.5, 1.0 |
```suggestion
| **Secondary Color** | The color used for drawing secondary grid lines. | (0-255, 0-255, 0-255) | (128,128,128) |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetSize' | Sets the size of the entire grid | Size :Float | None | Yes |
```suggestion
| 'SetSize' | Sets the size of the entire grid. | Size: Float | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetPrimarySpacing' | Sets spacing between primary grid lines | Spacing :Float | None | Yes |
```suggestion
| 'SetPrimarySpacing' | Sets spacing between primary grid lines. | Spacing: Float | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetSecondarySpacing' | Sets spacing between secondary grid lines | Spacing :Float | None | Yes |
```suggestion
| 'SetSecondarySpacing' | Sets spacing between secondary grid lines. | Spacing: Float | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetAxisColor' | Sets the color of the grid axis lines | Line Color :Color | None | Yes |
```suggestion
| 'SetAxisColor' | Sets the color of the grid axis lines. | Line Color: Color | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetPrimaryColor' | Sets the color of primary grid lines | Line Color :Color | None | Yes |
```suggestion
| 'SetPrimaryColor' | Sets the color of primary grid lines. | Line Color: Color | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'SetSecondaryColor' | Sets the color of secondary gridlines | Line Color :Color | None | Yes |
```suggestion
| 'SetSecondaryColor' | Sets the color of secondary gridlines. | Line Color: Color | None | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetSize' | Gets the size of the entire grid | None | Size :Float | Yes |
```suggestion
| 'GetSize' | Gets the size of the entire grid. | None | Size: Float | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetPrimarySpacing' | Gets spacing between primary grid lines | None | Spacing :Float | Yes |
```suggestion
| 'GetPrimarySpacing' | Gets spacing between primary grid lines. | None | Spacing: Float | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetSecondarySpacing' | Gets spacing between secondary grid lines | None | Spacing :Float | Yes |
```suggestion
| 'GetSecondarySpacing' | Gets spacing between secondary grid lines. | None | Spacing: Float | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetAxisColor' | Gets the color of the grid axis lines | None | Line Color :Color | Yes |
```suggestion
| 'GetAxisColor' | Gets the color of the grid axis lines. | None | Line Color: Color | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetPrimaryColor' | Gets the color of primary grid lines | None | Line Color :Color | Yes |
```suggestion
| 'GetPrimaryColor' | Gets the color of primary grid lines. | None | Line Color: Color | Yes |
```

2022-05-13 22:25 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| 'GetSecondaryColor' | Gets the color of secondary gridlines | None | Line Color :Color | Yes |
```suggestion
| 'GetSecondaryColor' | Gets the color of secondary gridlines. | None | Line Color: Color | Yes |
```

2022-05-13 23:25 UTC, FiniteStateGit approved these changes

2022-05-15 18:39 UTC, FiniteStateGit commented on content/docs/user-guide/components/reference/atom/grid.md
> +| Method Name | Description | Parameter | Return | Scriptable |
I missed this edit the first time, the method names should use backticks \` so that they are formatted as inline code.

2022-05-16 15:03 UTC, galibzon approved these changes
A picture of the viewport with the grid element would be nice. But this is good enough.

2022-05-16 19:08 UTC, merged