Add intermediate asset documentation
o3de/o3de.org pull request #1651
Opened 2022-05-18 20:32 UTC by amzn-mike

Signed-off-by: amzn-mike <80125227+amzn-mike@users.noreply.github.com>

## Change summary

Added documentation for intermediate assets feature

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-05-18 22:05 UTC, jackalbe approved these changes

2022-05-23 16:17 UTC, micronAMZN requested changes

2022-05-23 16:17 UTC, micronAMZN commented on content/docs/user-guide/assets/pipeline/intermediate-assets.md
> + * Due to the above limitations, if you want to output both types of products, your ProcessJob code will need to be careful to output ProductAssets for non-common platform jobs and IntermediateAssets
Minor edit.

```suggestion
* An output must be either an intermediate or a product asset, not both.  If you want to output both, you'll need to create 2 separate jobs in CreateJobs.
* Product assets cannot output for the Common platform.
* Intermediate assets must output for the Common platform.
* Due to the above limitations, if you want to output both types of products, your ProcessJob code must output ProductAssets for non-common platform jobs and IntermediateAssets for common platform jobs.
```

2022-05-23 16:17 UTC, micronAMZN commented on content/docs/user-guide/assets/pipeline/intermediate-assets.md
> +If you want to output platform-specific intermediates, the recommended method is to output all your intermediates with platform prefixes on the name, and then output an additional manifest file which
Minor edit.

```suggestion

If you want to output platform-specific intermediates, the recommended method is to output all your intermediates with platform prefixes on the name, and then output an additional manifest file which simply references all the other outputs. For example you might make a job which outputs `pc_myshader.bin`, `mac_myshader.bin`, and `myshader.shadermanifest`. You could then create another builder to consume these using `*.shadermanifest` as the input pattern.
```

2022-05-23 16:20 UTC, micronAMZN requested changes
We should add an entry for this topic in assets/pipeline/_index.md

2022-05-23 19:13 UTC, amzn-mike commented
> We should add an entry for this topic in assets/pipeline/_index.md

Added

2022-05-23 20:30 UTC, micronAMZN approved these changes

2022-05-31 05:40 UTC, merged