Asset Database documentation. Overview of what the Asset Database is,…
o3de/o3de.org pull request #1698
Opened 2022-06-10 20:16 UTC by AMZN-stankowi

## Change summary

Added a page describing the Asset Database, and how to make changes to the Asset Database. Some of this was originally written by [amzn-mike](https://github.com/amzn-mike).

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-06-20 21:02 UTC, micronAMZN requested changes

2022-06-24 14:58 UTC, AMZN-stankowi commented on content/docs/user-guide/assets/asset-processor/asset-database.md
> +### 1. Create Static Const Strings for the Query
That didn't work well when I tried to do the code blocks in the tutorial. Also, the nested steps don't seem to work well with that setup. Any idea on how to make that work?

With that change:
![image](https://user-images.githubusercontent.com/4838196/175562127-465c190b-ac5a-4de9-85f0-ec74ae6ead4b.png)


Without, as I had it originally:
![image](https://user-images.githubusercontent.com/4838196/175562232-2aacff53-87a8-4be5-8517-09d53b0829b3.png)

2022-06-24 19:40 UTC, AMZN-stankowi commented on content/docs/user-guide/assets/asset-processor/asset-database.md
> +weight: 200
Fixed

2022-06-24 19:40 UTC, AMZN-stankowi commented on content/docs/user-guide/assets/asset-processor/asset-database.md
> +The **Asset Database** is located in the [**Asset Cache**](docs/user-guide/assets/pipeline/asset-cache) for a project, in assetdb.sqlite.
Fixed

2022-06-24 19:40 UTC, AMZN-stankowi commented on content/docs/user-guide/assets/asset-processor/asset-database.md
> +# Asset Database Overview
Fixed

2022-06-30 18:52 UTC, FiniteStateGit approved these changes

2022-07-01 18:56 UTC, micronAMZN approved these changes

2022-07-01 18:56 UTC, merged