Minor formatting improvements
o3de/o3de.org pull request #1726
Opened 2022-06-17 19:54 UTC by willihay

Signed-off-by: William Hayward <wilhayw@amazon.com>

## Change summary

Just some minor grammar, style, and format improvements I made while reading some docs.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-06-17 23:30 UTC, FiniteStateGit requested changes
Inconsistent capitalization of sentence-initial words in code comments.
Line 20 - Insert space before 'bUseTerrain'.
Line 23 - Insert space before 'bUseTerrain'.
Line 40 - Change to 'idles for specified number of seconds'.
Line 53 - Insert space in 'returnsTrue'.
Line 73 - De-capitalize 'Entity'.
Line 76 - De-capitalize both occurrences of 'Entity'.
Line 82 - De-capitalize 'Entity'.
Line 91 - Insert space in 'EntityID' and De-capitalize 'Entity'.
Line 104 - Change to 'case-sensitive'.
Line 105 - Insert space in 'anymatch'.
Line 106 - Captialize 'IDs'. What does (AND) mean?
Line 117 - Insert space in 'ofthe'.
Line 120 - Capitalize 'editor'.
Line 140 - What does (DAG) mean?
Line 164 - Change 'kids' to children. Change 'realtive'.
Line 190 - Change to 'entities'.
Line 207 - De-capitalize 'Singleton'.
Line 230 - Captialize 'IDs'.
Line 235 - Captialize 'IDs'.
Line 268 - De-capitalize 'Entity'.
Line 274 - De-capitalize 'Entity'.
Line 276 - De-capitalize 'Component'.
Line 276 - De-capitalize 'Component'.
Welp.  I'll stop with the capitalization corrections here.
Line 488 - Remove s in '(typename)s'.
Line 585 - Change to 'asset root-relative'.

2022-06-17 23:30 UTC, FiniteStateGit commented on content/docs/user-guide/editor/editor-automation-examples.md
>   The editor automation API exposes a few methods to manage assets via the `azlmbr.asset.AssetCatalogRequestBus` bus.
```suggestion
 The Editor automation API exposes a few methods to manage assets via the `azlmbr.asset.AssetCatalogRequestBus` bus.
```

2022-06-21 14:33 UTC, micronAMZN approved these changes

2022-06-22 02:09 UTC, FiniteStateGit approved these changes

2022-06-22 02:09 UTC, merged