Add custom free function node migration instruction
o3de/o3de.org pull request #1756
Opened 2022-06-27 17:48 UTC by onecent1101

## Change summary
Adding instruction to guide user migrate from Generic Function Node to AutoGen Function Node.

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

Signed-off-by: onecent1101 <liug@amazon.com>

2022-06-27 18:33 UTC, carlitosan approved these changes

2022-06-27 22:45 UTC, willihay requested changes

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   </Function>
Per earlier suggestion, add an Out with a description for the IsClose function XML.

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +1. For ```SCRIPT_CANVAS_GENERIC_FUNCTION_MULTI_RESULTS_NODE(NODE_NAME, CATEGORY, UUID, DESCRIPTION, ...)``` use case
```suggestion
1. Example of replacing `SCRIPT_CANVAS_GENERIC_FUNCTION_MULTI_RESULTS_NODE`:
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   Replacement function and ScriptCanvasFunction.xml content
```suggestion
   Replacement function and ScriptCanvasFunction.xml content:
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   AZStd::tuple<Data::Vector3Type, Data::Vector3Type, Data::Vector3Type> GetRows(const Data::Matrix3x3Type& source);
Per earlier suggestion:
```suggestion
   AZStd::tuple<Data::Vector3Type, Data::Vector3Type, Data::Vector3Type> GetRows(const Data::Matrix3x3Type& source) { ... }
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   </Function>
Per earlier suggestion, add an Out with a description for the GetRows function XML.

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +Update Generic Function Node macros by providing replacement node identifier, and replacement node identifier comes from ScriptCanvasFunction.xml. We use Namespace and Function Name to guarantee the
Step 3's description is the same as step 2. Did you mean this?
```suggestion
### Step 3: Update generic function node macros
Replace each generic function node macro with the `SCRIPT_CANVAS_GENERIC_FUNCTION_REPLACEMENT` macro, using a sanitized replacement node identifier that's derived from ScriptCanvasFunction.xml. We use `Namespace` and `Function Name` to guarantee the uniqueness.
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +* Function Name: ```GetRow```, ```GetRows```, ```IsClose```
```suggestion
* Function Names: `GetRow`, `GetRows`, `IsClose`
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +* Namespace: ```ScriptCanvas::Matrix3x3Functions```
```suggestion
* Namespace: `ScriptCanvas::Matrix3x3Functions`
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +Sanitized replacement node identifiers are: ```ScriptCanvas_Matrix3x3Functions_GetRow```, ```ScriptCanvas_Matrix3x3Functions_GetRows```, ```ScriptCanvas_Matrix3x3Functions_IsClose```
```suggestion
The sanitized replacement node identifiers are: `ScriptCanvas_Matrix3x3Functions_GetRow`, `ScriptCanvas_Matrix3x3Functions_GetRows`, and `ScriptCanvas_Matrix3x3Functions_IsClose`.
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +### Step 4: Upgrade existing out of date Graph
```suggestion
### Step 4: Upgrade existing graphs that are now out of date
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +At this point, system gets all required information to do the replacement and there are two ways to upgrade Graph:
```suggestion
At this point, the system has all the required information to do the replacement. To upgrade your graphs, do one of the following:
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +1. Batch Processing - For convenience you can use the version explorer tool found in the ScriptCanvas Editor ```Tools / Upgrade Graphs```. You can select multiple source Graphs in the tool and upgrad
```suggestion
1. Batch Processing - For convenience you can use the version explorer tool found in Script Canvas Editor in the **Tools / Upgrade Graphs** menu. You can select multiple source graphs in the tool and upgrade them all to the latest version. The tool will save them in the new format, or report errors if the upgrade fails.
```

2022-06-27 22:45 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +1. Single Processing - You can open specific Graph in the ScriptCanvas Editor, Graph will be automated upgraded, and you should be able to save it with new format.
```suggestion
1. Single Processing - You can open a specific graph in Script Canvas Editor. The graph will upgrade automatically. Save the graph to keep the new format.
```

2022-06-28 17:51 UTC, onecent1101 commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   </Function>
Actually there is no `Out` element and we do have `Description` attribute, the main thought here is to show replacement required fields. (Introducing `Parameter` as it is required for DefaultValue use case)
We do recommend customer to use `Text Replacement` as the way to modify editor data, like naming and description which is introduced as last part of previous topic.

2022-06-28 22:13 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-free-function-nodes.md
> +   </Function>
OK, not a hard request I guess. I was just leaning towards showing readers how to migrate as much of the original code as possible, for a more complete example of a migration. I'm surprised this helpful "out param" description wasn't kept as part of the actual migration of these nodes.

2022-06-28 22:31 UTC, willihay approved these changes
Content and updates from feedback reviewed and approved. Deferring to assigned editor for further editorial review.

2022-06-30 21:43 UTC, merged