Created CMake Essentials Series Part 2 Blog
o3de/o3de.org pull request #1760
Opened 2022-06-28 19:32 UTC by aFinchy

## Change summary

Added Blog CMake Essentials Series - Part 2

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-06-30 16:07 UTC, hultonha approved these changes
I'm super biased but approving anyway 😅 Thanks so much for getting these published @aFinchy

2022-07-01 19:21 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +## Topic
First header not needed and just looks odd in the summary page.
```suggestion
## Topic
```

2022-07-01 19:37 UTC, willihay requested changes

2022-07-01 19:37 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +The killer feature that makes dependency management a breeze is `FetchContent`. Let's pick-up where we left off in the last part by adding some useful functionality to our 'Hello, World!' application
```suggestion
The killer feature that makes dependency management a breeze is `FetchContent`. Let's pick up where we left off in the last part by adding some useful functionality to our 'Hello, World!' application. Suppose we'd like to make use of an iterator library but don't want to have to copy it into our source tree and manually configure it to build ourselves. This is how we'd achieve it with `FetchContent` (new code follows the `project` command from [Part 1](/blog/posts/cmake-essentials-series-part-1)).
```

2022-07-01 19:37 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +First we need to bring the CMake `FetchContent` module into our `CMakeLists.txt` file (`#1`). We then declare the library we'd like to use with `FetchContent_Declare` (`#2`). We give the dependency a
```suggestion
First we need to bring the CMake `FetchContent` module into our `CMakeLists.txt` file (`#1`).

We then declare the library we'd like to use with `FetchContent_Declare` (`#2`).

We give the dependency a name (`#3`) and point it to the git repo of the library we'd like to use (`#4`) (`GIT_REPOSITORY` is only one of many options such as `SOURCE_DIR` for a local path).

Finally it's good practice to pin the version of the library to a specific commit (or a tag if one exists) (`#5`) so subsequent upstream changes don't break us immediately.

`FetchContent_MakeAvailable` (`#6`) then does quite a lot of work behind the scenes but essentially just makes the targets available to be used by our application.

The last thing we need to do is just link against the dependency (`#7`). The great thing about this is that as long as the project we're depending on has been set up correctly, there's no need to touch include or library paths, everything is handled upstream and isn't our concern.  
```

2022-07-01 19:37 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +With that we can write an improved 'Hello, \<planet\>' program that outputs the index at each iteration
```suggestion
With that we can write an improved 'Hello, \<planet\>' program that outputs the index at each iteration.
```

2022-07-01 19:37 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +`FetchContent` is fantastic for small simple libraries that are fast to build. The dependency is built directly along with our application (the dependencies actually wind up in `build/_deps`). For la
```suggestion
`FetchContent` is fantastic for small, simple libraries that are fast to build. The dependency is built directly along with our application. (The dependencies actually wind up in `build/_deps`.) For larger dependencies we might want to build them separately first at an earlier stage and then bring them in with the `find_package` command (more on this next time...). `FetchContent` also only works with projects that build using CMake, although the vast majority now do and even those that don't often have community maintained CMake versions. Check out [bgfx.cmake](https://github.com/bkaradzic/bgfx.cmake) as an example.
```

2022-07-01 19:37 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-2.md
> +There's also another intro CMake video titled ['CMake for Dummies'](https://youtu.be/7W4Q-XLnMaA) (_the video quality isn't the best but does a great job covering the basics of using CMake_).
```suggestion
There's also another intro CMake video titled ['CMake for Dummies'](https://youtu.be/7W4Q-XLnMaA). (_The video quality isn't the best but it does a great job covering the basics of using CMake_.)
```

2022-07-01 22:26 UTC, FiniteStateGit approved these changes

2022-07-05 20:50 UTC, willihay approved these changes

2022-07-05 20:51 UTC, merged