Created CMake Essentials Series Part 4 Blog
o3de/o3de.org pull request #1762
Opened 2022-06-28 19:32 UTC by aFinchy

## Change summary

Added Blog CMake Essentials Series - Part 4

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-06-30 16:09 UTC, hultonha approved these changes
I'm super biased but approving anyway 😅 Thanks so much for getting these published @aFinchy (also noticed this and the previous post might need the heading change to two '##' instead of just one)

2022-07-01 19:22 UTC, willihay commented on content/blog/posts/cmake-essentials-series-part-4.md
> +## Topic
First header not needed and just looks odd in the summary page.
```suggestion
```

2022-07-01 22:24 UTC, FiniteStateGit requested changes

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +We then have to bring in some standard install location paths to ensure installing is portable, these are made available by include `GNUInstallDirs` (`#3`)
```suggestion
We then have to bring in some standard install location paths to ensure installation is portable, these are made available by include `GNUInstallDirs` (`#3`).
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +Next we setup the include paths for the library (`#4`). Notice we use a generator expression (perhaps the topic of another ly-goodreads sometime in the future) to configure where to look for the incl
```suggestion
Next we setup the include paths for the library (`#4`). Notice we use a generator expression (perhaps the topic of another blog post sometime in the future) to configure where to look for the includes. 

This is either as an imported target (`#5`) being used after install or part of the normal build (distinguished by `BUILD_INTERFACE` and `INSTALL_INTERFACE`).
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +The last three steps are the illusive `install` commands. We begin by specifying the target to install (`#6`). We set the export name (which does not need to match the target name but often does) whi
```suggestion
The last three steps are the illusive `install` commands. We begin by specifying the target to install (`#6`). We set the export name (which does not need to match the target name but often does) which is the name CMake looks for when we use `find_package`. We also specify where the built library file should be installed (`${CMAKE_INSTALL_LIBDIR}` is provided by `GNUInstallDirs`). 

We next have to install (copy) the export file to the install location (`#7`). It’s good practice to set a namespace at this point so clients must use `calculator::calculator` to identify it as an imported target and we must also set the location of where the export file should be installed. 

The final invocation of `install` (`#8`) just copies the interface/header files to the expected location.
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +Hopefully this tour of CMake and some of its lesser known features has been useful. The content might not be useful today but will no doubt only become more relevant in future. If there are any quest
```suggestion
Hopefully this tour of CMake and some of its lesser known features has been useful. The content might not be useful today but will no doubt only become more relevant in future. If there are any questions or follow-ups about things that weren’t covered please get in touch on the O3DE Discord.
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +To learn more about installing I recommend watching this excellent talk by Craig Scott
```suggestion
To learn more about installing I recommend watching this excellent talk by Craig Scott:
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +There’s also a lot more information on the repo mentioned last week with plenty of examples
```suggestion
There’s also a lot more information on the repo mentioned last week with plenty of examples:
```

2022-07-01 22:24 UTC, FiniteStateGit commented on content/blog/posts/cmake-essentials-series-part-4.md
> +There’s also a little set of CMake install helpers available here that take some of the boilerplate out of installing a new library
```suggestion
There’s also a little set of CMake install helpers available here that take some of the boilerplate out of installing a new library:
```

2022-07-01 22:29 UTC, FiniteStateGit approved these changes

2022-07-01 22:29 UTC, merged