Update scriptcanvas nodeable node doc
o3de/o3de.org pull request #1782
Opened 2022-07-06 21:21 UTC by onecent1101

## Change summary
* Update scriptcanvas nodeable doc with new registry guide
* Update scriptcanvas nodeable doc with easy example, and move Timer node example to advanced topic

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

Signed-off-by: onecent1101 <liug@amazon.com>

2022-07-07 20:11 UTC, willihay requested changes

2022-07-07 20:11 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +We'll use the following XML, copied from the O3DE source for the **Time Delay** node.
```suggestion
If you have shared logic across multiple nodeable nodes, you can create a base node and multiple derived nodes.

The following example uses the O3DE source for the **Time Delay** node:
```

2022-07-07 20:11 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +The `TimeDelayNodeable` class itself implements a base class, called `BaseTimer`. In the following XML, you can see the base class defines shared properties
```suggestion
The `TimeDelayNodeable` class implements a base class, called `BaseTimer`. In the following base class XML, you can see that the base class defines the shared properties, "Units" and "TickOrder":

File: [BaseTimer.ScriptCanvasNodeable.xml](https://github.com/o3de/o3de/blob/development/Gems/ScriptCanvas/Code/Include/ScriptCanvas/Internal/Nodeables/BaseTimer.ScriptCanvasNodeable.xml)

```

2022-07-07 20:11 UTC, willihay commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +For further node name, tooltip and category customization, please refer to [Text Replacement](/docs/user-guide/scripting/script-canvas/editor-reference/text-replacement/)
```suggestion
For further node name, tooltip, and category customization, please refer to [Text Replacement](/docs/user-guide/scripting/script-canvas/editor-reference/text-replacement/).
```

2022-07-18 22:25 UTC, onecent1101 commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +       *.ScriptCanvasNodeable.xml,ScriptCanvasNodeableRegistry_Header.jinja,AutoGenNodeableRegistry.generated.h
Actually we don't expect customer to use ScriptCanvasGrammar, right now ScriptCanvasGrammar is all for our internal usage and it is not a nodeable node.

Plus StartingPointInput Gem ScriptCanvasGrammar usage is even for deperecation. (We don't have any other Gem as a good reference)

2022-07-18 22:25 UTC, onecent1101 commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +
REGISTER_SCRIPTCANVAS_AUTOGEN_FUNCTION is for custom function node which is covered by a different topic

REGISTER_SCRIPTCANVAS_AUTOGEN_GRAMMAR is for internal usage right now only, and some use case is related to deprecation node.

2022-07-18 22:25 UTC, onecent1101 commented on content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/custom-nodeable-nodes.md
> +    REGISTER_SCRIPTCANVAS_AUTOGEN_FUNCTION(MyGemStatic)
good catch, copy paste mistake, for nodeable usage, we just need Nodeable related header and macros

2022-07-19 16:23 UTC, merged