Creation of the Epic Joining O3DF Blog
o3de/o3de.org pull request #1799
Opened 2022-07-19 17:15 UTC by aFinchy

## Change summary

Creation of the Epic Joins O3DF Blog. 

****MUST BE MERGED JULY 20, 7AM - 9AM**

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-07-19 20:35 UTC, FiniteStateGit requested changes

2022-07-19 20:35 UTC, FiniteStateGit commented on content/blog/posts/epic-joins-o3df.md
> +Founded in 2000, the Linux Foundation is supported by more than 1,000 members and is the world’s leading home for collaboration on open source software, open standards, open data, and open hardware.
```suggestion
Founded in 2000, the Linux Foundation is supported by more than 1,000 members and is the world’s leading home for collaboration on open source software, open standards, open data, and open hardware. Linux Foundation’s projects are critical to the world’s infrastructure including Linux, Kubernetes, Node.js, and more. The Linux Foundation’s methodology focuses on leveraging best practices and addressing the needs of contributors, users and solution providers to create sustainable models for open collaboration. For more information, please visit us at [linuxfoundation.org](linuxfoundation.org).
```

2022-07-19 20:35 UTC, FiniteStateGit commented on content/blog/posts/epic-joins-o3df.md
> +Established in July 2021, the mission of the Open 3D Foundation (O3DF) is to make an open-source, fully-featured, high-fidelity, real-time 3D engine for building games and simulations, available to e
```suggestion
Established in July 2021, the mission of the Open 3D Foundation (O3DF) is to make an open-source, fully-featured, high-fidelity, real-time 3D engine for building games and simulations, available to every industry. The Open 3D Foundation is home to the O3D Engine project. To learn more, please visit [o3d.foundation](o3d.foundation).
```

2022-07-19 20:35 UTC, FiniteStateGit commented on content/blog/posts/epic-joins-o3df.md
> +O3D Engine is the flagship project managed by the Open 3D (O3D) Foundation. The open-source project is a modular, cross-platform 3D engine built to power anything from AAA games to cinema-quality 3D
```suggestion
O3D Engine is the flagship project managed by the Open 3D (O3D) Foundation. The open-source project is a modular, cross-platform 3D engine built to power anything from AAA games to cinema-quality 3D worlds to high-fidelity simulations. The code is hosted on GitHub under the Apache 2.0 license. To learn more, please visit [o3de.org](o3de.org).
```
The call to action to visit o3de.org is a bit odd as this blog is posted on o3de.org.

2022-07-19 20:35 UTC, FiniteStateGit commented on content/blog/posts/epic-joins-o3df.md
> +Anyone interested in the O3D Engine is invited to get involved and connect with the community on Discord.com/invite/o3de and GitHub.com/o3de.
```suggestion
Anyone interested in the O3D Engine is invited to get involved and connect with the community on [Discord.com/invite/o3de](Discord.com/invite/o3de) and [GitHub.com/o3de](https://github.com/o3de). 
```

2022-07-19 21:56 UTC, FiniteStateGit commented on content/blog/posts/epic-joins-o3df.md
> +O3D Engine is the flagship project managed by the Open 3D (O3D) Foundation. The open-source project is a modular, cross-platform 3D engine built to power anything from AAA games to cinema-quality 3D
```suggestion
O3D Engine is the flagship project managed by the Open 3D (O3D) Foundation. The open-source project is a modular, cross-platform 3D engine built to power anything from AAA games to cinema-quality 3D worlds to high-fidelity simulations. The code is hosted on GitHub under the Apache 2.0 license.
```

2022-07-19 23:47 UTC, FiniteStateGit approved these changes

2022-07-20 15:53 UTC, sptramer approved these changes

2022-07-20 16:10 UTC, merged