Material Node - Updated a deprecated screenshot
o3de/o3de.org pull request #1856
Opened 2022-07-28 13:56 UTC by LB-ArturZieba

Signed-off-by: Artur Zięba <86952082+LB-ArturZieba@users.noreply.github.com>

## Change summary

* Material Node (https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/nodes-material/):
   * Updated a deprecated screenshot under the "To add a Material node in the Track View section".

### Submission Checklist:

* [X] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [X] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [X] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [X] **Help the user** - Does the documentation show the user something *meaningful*?

2022-07-28 15:05 UTC, FiniteStateGit requested changes

2022-07-28 15:05 UTC, FiniteStateGit commented on content/docs/user-guide/visualization/cinematics/track-view/nodes-material.md
>  ![Copy the material name path in the Material Editor.](/images/user-guide/cinematics/cinematics-track-view-nodes-material-4.png)
```suggestion

    ![Copy the material name path in the Material Editor.](/images/user-guide/cinematics/cinematics-track-view-nodes-material-4.png)
```
Images and the opening tag of shortcodes like {{< note >}} need to be indented 4 spaces to be properly aligned and spaced in lists.

2022-08-02 09:20 UTC, LB-ArturZieba commented
Verified the suggested whitespace changed on localhost, and it retains the numbered list fix. Thanks for the explanation!

2022-08-02 19:13 UTC, FiniteStateGit approved these changes

2022-08-03 16:52 UTC, sptramer approved these changes

2022-08-03 16:52 UTC, merged

2022-08-04 08:49 UTC, LB-ArturZieba commented
Pull request merge verified as successful.