SSAO component documentation
o3de/o3de.org pull request #1858
Opened 2022-07-29 00:03 UTC by antonmic

Signed-off-by: antonmic <56370189+antonmic@users.noreply.github.com>

2022-07-29 23:20 UTC, galibzon approved these changes

2022-08-04 23:07 UTC, chanmosq requested changes

2022-08-04 23:07 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/ssao.md
> +| **Blur Edge Threshold** | An edge threshold can be specified for the blur to ignore depth changes of a certain value. This has the most effect at small values. |
"can be specified" - Does that mean we can not choose to not activate this, even with blur enabled? 

Current suggestion to rephrase assumes that it's activated if blur is enabled. And I assume that at `0.0`, it has the most effect?
```suggestion
| **Blur Edge Threshold** | An edge threshold, in which the blur ignores depth changes at the specified value. This has the most effect with smaller values. |
```

2022-08-04 23:07 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/ssao.md
> +| **Enable Downsample** | Whether to downsample the depth buffer and perform SSAO and blur on the downsampled result before upsampling. This is an optimization that results in less detailed SSAO. |
```suggestion
| **Enable Downsample** | If enabled, first downsamples the depth buffer and performs SSAO and blur on the downsampled result, then upsamples the result. This is an optimization that results in a less detailed SSAO. |
```

2022-08-11 07:33 UTC, micronAMZN requested changes
Agree with @chanmosq suggestions. Also, the property table should have Value and Default columns. See other component docs for examples.

2022-08-23 21:15 UTC, chanmosq approved these changes

2022-08-27 07:34 UTC, micronAMZN approved these changes

2022-08-27 07:36 UTC, micronAMZN approved these changes

2022-08-27 07:36 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/ssao.md
> +| Property | Description | Values | Default
```suggestion
| Property | Description | Values | Default |
```

2022-08-27 07:36 UTC, merged