HttpRequestorGem: Add instructions about how to setup runtime dependencies on gem
o3de/o3de.org pull request #1959
Opened 2022-09-07 23:43 UTC by lmbr-pip

## Change summary

Was asked for by contributor, fixes https://github.com/o3de/o3de.org/issues/1920

* small tweaks to http requestor documentation

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-09-07 23:56 UTC, willihay commented
The content in this PR is applicable to both the current and next release, therefore since we're in the stabilization period for the next release, it should target either main or stabilization/22.10.

2022-09-07 23:59 UTC, willihay requested changes
The content in this PR is applicable to both the current and next release, therefore since we're in the stabilization period for the next release, it should target either main or stabilization/22.10.

2022-09-07 23:59 UTC, willihay commented on content/docs/user-guide/gems/reference/network/http-requestor.md
> +```
```suggestion
```cpp
```

2022-09-08 02:32 UTC, micronAMZN approved these changes
Approved pending requested change.

2022-09-08 16:12 UTC, lmbr-pip commented
I will retarget to main (if possible) - as its for the current feature it should go there.

2022-09-08 16:15 UTC, willihay approved these changes

2022-09-12 16:30 UTC, willihay commented
RE: Retargeting to main, I've heard several people say that they've had to do so in a new PR. One suggested creating a new branch that targets main, then cherry-picked commits over from the branch they used for the original PR. For small PRs like this one, it might be easiest to manually redo changes from a new branch.

2022-09-22 17:28 UTC, lmbr-pip commented
Retargetting to stablization in: https://github.com/o3de/o3de.org/pull/1989

2022-09-22 17:28 UTC, closed without merging