Fix overview.md / _index.md issues
o3de/o3de.org pull request #1962
Opened 2022-09-08 19:46 UTC by chanmosq

## Change summary

This PR resolves a content architecture issue, see discussion in https://github.com/o3de/o3de.org/issues/1685.

**Note**: There are no content changes, even though it shows many line changes. The content from overview.md was moved to _index.md, and overview.md was deleted. 

**Check!**
To verify the contents in _index.md are the same as previous overview.md, run the following commands:

```
git diff HEAD:./content/docs/contributing/to-code/overview.md content/docs/contributing/to-code/_index.md

git diff HEAD:./content/docs/contributing/to-docs/overview.md content/docs/contributing/to-docs/_index.md

git diff HEAD:./content/docs/contributing/to-docs/style-guide/overview.md content/docs/contributing/to-docs/style-guide/_index.md

git diff HEAD:./content/docs/tools-ui/ux-patterns/component-card/overview.md content/docs/tools-ui/ux-patterns/component-card/_index.md

git diff HEAD:./content/docs/tools-ui/ux-patterns/error/overview.md content/docs/tools-ui/ux-patterns/error/_index.md

git diff HEAD:./content/docs/user-guide/gems/overview.md content/docs/user-guide/gems/_index.md
```
### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [X] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-09-08 21:07 UTC, micronAMZN approved these changes
Nicely done!

2022-09-08 21:21 UTC, willihay requested changes
I recommend adding redirects for some of the deleted overview pages, in case anyone has linked to them. I suggest adding at least the following to static\_redirects:
/docs/contributing/to-code/overview  /docs/contributing/to-code
/docs/contributing/to-docs/overview  /docs/contributing/to-docs
/docs/contributing/to-docs/style-guide/overview  /docs/contributing/to-docs/style-guide
/docs/user-guide/gems/overview  /docs/user-guide/gems
/docs/user-guide/gems/reference/overview  /docs/user-guide/gems/reference

2022-09-14 19:16 UTC, willihay requested changes

2022-09-14 19:16 UTC, willihay commented on .gitignore
> +/styles/
Intended for a different PR maybe?
```suggestion
```

2022-09-14 19:26 UTC, willihay approved these changes

2022-09-14 19:27 UTC, merged