'For the Love of the Game' Blog (CCI)
o3de/o3de.org pull request #1973
Opened 2022-09-16 02:34 UTC by uoduckswtd1

## Change summary

### Submission Checklist:

* [X] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [X] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [X] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [X] **Help the user** - Does the documentation show the user something *meaningful*?

2022-09-16 06:39 UTC, aFinchy commented
**What do you need to do?**
If you have a PR that is failing DCO checks, you can follow the instructions in the “Checks” tab for DCO to create a remediation commit or with these instructions:
1.    Create a new commit (can be empty, but should be avoided) with the following message:
```
DCO Remediation Commit for <Your Github name> <Your Github email>
I, <Your Github name> <Your Github email>, hereby add my Signed-off-by to this commit: <Unsigned commit hash>
Signed-off-by: <Your Github name> <Your Github email>
```
2.    If you have multiple commits that are not signed-off, you can batch them into the same commit, with the same message and different hash on each line
3.    Ensure this commit is signed off, then push the commit to your branch. The DCO check should now mark those commits as signed off.

2022-09-16 15:47 UTC, sptramer requested changes

2022-09-16 15:47 UTC, sptramer commented on content/blog/posts/for-the-love-of-the-game.md
> +![CCI-indie-developers](/static/images/blog/CCI/CCI-blog-image.png)
Images do not require the `/static` path in the link, and won't render if it's included.

```suggestion
![CCI-indie-developers](/images/blog/CCI/CCI-blog-image.png)
```

2022-09-16 15:48 UTC, sptramer approved these changes
Approved provided that the DCO is fixed for merge.

2022-09-16 18:56 UTC, aFinchy requested changes
Left a bunch of formatting comments. 

The image that is in the same folder as the blog must be removed. Keep all images in the Static folder only.

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +blog_img: "/images/blog/announcement_thumbnail.jpg"
Remove duplicate line.
`blog_img: "/images/blog/announcement_thumbnail.jpg"`

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +**Jacob:**  My first recommendation would be to pull up the [documentation](https://www.o3de.org/docs/) and get started because, like we said, the onboarding is smooth and easy to understand. If you
Docs are internal, Change 
`[documentation](https://www.o3de.org/docs/) `
to
`[documentation](/docs/) `

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +**Jacob:**  While neither of us have direct, hands-on experience with adding gems and capabilities specifically in O3DE that aren’t built into the Engine, we've done similar things in other engines a
Doc link is internal, Change to internal link, not external
Change:
`[networking](https://docs.o3de.org/docs/user-guide/networking/)`
to
`[networking](/docs/user-guide/networking/)`

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +Onboarding in O3DE, on a scale of 1-5, was a five because we found that the [documentation](https://www.o3de.org/docs/) was great, better than anything else we’d experienced. When using other engines
Docs are internal, Change 
`[documentation](https://www.o3de.org/docs/) `
to
`[documentation](/docs/) `

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +Born out of a desire to make their own games, indie game developers Jacob Dodenhoff and Phoenix Cook forged [Chaotic Creations Interactive](https://www.chaoticcreationsinteractive.com/) (CCI), a **sm
Change the Open 3D Engine link to Internal, not external.

2022-09-16 18:56 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +blog_img: "/images/blog/announcement_thumbnail.jpg"
I would suggest having a Blog image instead of defaulting to the bland default image. This image is very outdated and needs a refresh.

2022-09-16 19:03 UTC, aFinchy commented on content/blog/posts/for-the-love-of-the-game.md
> +date: 2022-09-16
Change date to the 21st

2022-09-16 19:13 UTC, FiniteStateGit approved these changes

2022-09-20 17:07 UTC, OBWANDO approved these changes

2022-09-20 19:08 UTC, aFinchy approved these changes
Fixed all the changes myself, and built locally as i found the image was also a bit too large. After all my changes, I approve now.

2022-09-21 16:46 UTC, merged