AzAutoGen build docs
o3de/o3de.org pull request #2005
Opened 2022-09-29 20:46 UTC by chanmosq

Signed-off-by: chanmosq <75444793+chanmosq@users.noreply.github.com>

## Change summary

Note: This PR contains broken links, however that page is being added in another PR (https://github.com/o3de/o3de.org/pull/2004)

This topic is about how to include AzAutoGen in a target build for your project or Gem. 

It is revived from an old PR (https://github.com/o3de/o3de.org/pull/1365) and incorporates previous feedback, as well as newly added information.

### Submission Checklist:

* [X] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [X] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [X] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [X] **Help the user** - Does the documentation show the user something *meaningful*?

2022-10-03 15:28 UTC, micronAMZN approved these changes
Three minor suggestions.

2022-10-03 15:28 UTC, micronAMZN commented on content/docs/user-guide/build/generated-source.md
> +AzAutoGen invokes when CMake builds an O3DE target. To invoke AzAutoGen and generate the output source files for your project or Gem, complete the following steps:
Finding the wording here a bit odd. A suggestion

```suggestion
AzAutoGen is invoked when CMake builds an O3DE target. To invoke AzAutoGen and generate the output source files for your project or Gem, complete the following steps:
```

2022-10-03 15:28 UTC, micronAMZN commented on content/docs/user-guide/build/generated-source.md
> +An *autogen rule* instructs CMake to generate files by using AzAutoGen.
minor suggestion

```suggestion
An *autogen rule* instructs CMake to use AzAutoGen to generate files. 
```

2022-10-03 15:28 UTC, micronAMZN commented on content/docs/user-guide/build/generated-source.md
> +To do this you can add an autogen step to any build target by calling the `ly_add_autogen()` CMake command.
```suggestion
To do this, you can add an autogen step to any build target by calling the `ly_add_autogen()` CMake command. 
```

2022-10-06 01:02 UTC, sptramer requested changes

2022-10-17 16:26 UTC, JwGedit requested changes
Edit pass complete

2022-10-31 21:51 UTC, chanmosq commented on content/docs/user-guide/build/generated-source.md
> +In order to use AzAutoGen, you must provide Jinja templates and XML or JSON data files that AzAutoGen can generate output files from. The contents of these files depend on your intended purpose for u
Combination of both suggestions

```suggestion
To use AzAutoGen, you must provide Jinja templates and XML or JSON data files that AzAutoGen can generate output files from. The contents of these files depend on your intended purpose for using AzAutoGen. For a complete description of how AzAutoGen works and how to write templates and data inputs for generation, refer to [Automate Source Generation from Templates with AzAutoGen](/docs/user-guide/programming/autogen/). 
```

2022-11-01 19:37 UTC, kberg-amzn commented on content/docs/user-guide/build/generated-source.md
> +This associates a target with a set of autogen rules and gives an explicit list of the generated output files to include in the target build.
At target definition is probably cleaner and easier to maintain longer term.

2022-11-03 21:35 UTC, sptramer approved these changes

2022-11-04 16:18 UTC, lumberyard-employee-dm reviewed
This document looks good to me.
Just one comment about documening the `OUTPUT_NAME` parameter for the `ly_add_autogen` command

2022-11-04 16:25 UTC, lumberyard-employee-dm commented on content/docs/user-guide/build/generated-source.md
> +Most of the time, you want to run AzAutoGen by passing autogen rules into `ly_add_target()`, as outlined in the [Integrating with an O3DE build target](#integrating-with-an-o3de-build-target) section
The `#integrating-with-an-o3de-build-target` reference doesn't appear to be jumping to that section in the deployment preview.

2022-11-04 16:26 UTC, lumberyard-employee-dm commented on content/docs/user-guide/build/generated-source.md
> +* `$file`: The full name of the input file. This is equivalent to running the UNIX shell command `basename $file`.
For `$fileprefix`, we state that it is the name of the "current file", but for `$file` we state it is the full name of the "input file".
For consistency we should probably use "current input file" for both.

2022-11-04 16:31 UTC, lumberyard-employee-dm commented on content/docs/user-guide/build/generated-source.md
> +* `$path`: The path to the final output destination.
We can reiterate that the `$path` corresponds to the `${CMAKE_CURRENT_BINARY_DIR}/Azcg/Generated` directory from line 25 of this doc.

2022-11-04 16:59 UTC, lumberyard-employee-dm approved these changes
I am satisfied with changes

2022-11-04 17:24 UTC, merged