{lyn11017} Scene pipeline documentation
o3de/o3de.org pull request #2017
Opened 2022-10-03 19:14 UTC by jackalbe

## Change summary
This is the documentation for the Scene Pipeline inside the asset processing system. The User Defined Properties system was also moved to the Scene Pipeline documentation.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-10-04 17:14 UTC, AMZN-stankowi approved these changes

2022-10-04 17:58 UTC, junbo75 approved these changes

2022-10-04 17:58 UTC, junbo75 commented on content/docs/user-guide/assets/scene-pipeline/scene-builder.md
> +The the scene is loaded via the LoadingComponent components, the GenerationComponent events are emitted when the scene pipeline wants scene builders to modify node contents or add nodes to the SceneG
Typo: Remove the second "the" at the beginning of this sentence :)

2022-10-06 22:01 UTC, micronAMZN requested changes
In addition to the comments, please do a pass ensuring consistent use of terminology and style for key terms. For example: SceneGraph, `SceneGraph`, Scene graph, and scene graph are used interchangeably in these topics. Other examples SceneAPI,  SceneManifest, and so on. Please also, ensure consistent usage of code tags for API terms and methods as well.

2022-10-11 15:50 UTC, micronAMZN approved these changes

2022-10-11 15:50 UTC, merged