Revised setup instructions for Kythera AI Gem
o3de/o3de.org pull request #2082
Opened 2022-11-11 18:40 UTC by robindouglasjohnson

Signed-off-by: Robin Johnson <robinj@kythera.ai>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-11-17 17:46 UTC, sptramer commented
@robindouglasjohnson Under the new sig-docs-community review guidelines (https://github.com/o3de/sig-docs-community/issues/74), we will need a technical reviewer from Kythera. In addition, you should be aware of ongoing discussions with the TSC (in meeting notes) and sig-docs-community (https://github.com/o3de/sig-docs-community/issues/72) regarding the documentation of Gems not included in the core O3DE distribution.

2022-11-21 20:07 UTC, sptramer requested changes
Some copy changes, minor formatting fixes, and needed improvements before merge. Thanks!

2022-11-21 20:07 UTC, sptramer commented on content/docs/user-guide/gems/reference/kythera-ai/setup/installer.md
> +Go to the O3DE editor. Find your project and select “Configure Gems”. 
```suggestion
Go to the O3DE Editor. Find your project and select “Configure Gems”. 
```

2023-01-05 18:17 UTC, FiniteStateGit approved these changes

2023-02-07 17:48 UTC, sptramer requested changes
Old change requests were not addressed in the updates; Please make sure that you're submitting the changes correctly. If you want to directly accept the suggestions through the GitHub UI, you can use the [commit suggestion](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) feature. Some of the issues (like specific wait times) still need to be addressed manually.

2024-07-03 20:00 UTC, ShaunaGordon commented
@RoddieKieley Close this one without merging, for the following reasons:

- Decision by the TSC to not include detailed resources for 3rd Party Gems
- Kythera's switch from free to paid for this Gem, which further runs counter to our guidelines for what to include in our docs

@robindouglasjohnson If you have this available as part of a collection of tutorials available on the Kythera website, or elsewhere, we'll happily link to it.

2024-07-03 20:53 UTC, robindouglasjohnson commented
I no longer work for Kythera so I can't help, sorry.

2024-07-03 22:59 UTC, ShaunaGordon commented
@robindouglasjohnson No worries. Thanks for letting me know. 

---

For reference purposes, I've reached out to Kythera via their contact form to see if they have any input.

2024-08-22 18:36 UTC, ShaunaGordon commented
I've spoken with the current Kythera team, and because of changes in both Kythera and O3DE policy, we'll be removing detailed Kythera documentation and instead linking to their own content.

2024-08-22 18:36 UTC, closed without merging