fixed broken link
o3de/o3de.org pull request #2104
Opened 2022-11-19 22:17 UTC by chchrist

Signed-off-by: Tolis Christomanos <christomanos@gmail.com>

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-11-20 07:23 UTC, FiniteStateGit approved these changes
Thanks for the contribution!

2022-11-21 17:05 UTC, sptramer requested changes
The link is also broken at `content/docs/user-guide/gems/reference/aws/aws-gamelift/_index.md`, can you fix it there as well please?

Thanks for your submission!

2022-11-28 18:07 UTC, willihay commented
> The link is also broken at `content/docs/user-guide/gems/reference/aws/aws-gamelift/_index.md`, can you fix it there as well please?
 
The broken link in GameLift _index will be addressed in https://github.com/o3de/o3de.org/pull/2109.
To avoid creating a merge conflict, let's _not_ add it to this PR.
@sptramer Recommend withdrawing your change request and approving as is. Thanks!

2022-11-28 18:20 UTC, sptramer approved these changes

2022-11-28 18:20 UTC, merged