[Amazon GameLift] Fix typos, remove previous and next links
o3de/o3de.org pull request #2109
Opened 2022-11-22 17:56 UTC by lmbr-pip

Fixes typos, non-standard previous and next links and added some context

Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

## Change summary

Fixes typos, non-standard previous and next links and added some context to the GameLift Gem documents

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2022-11-22 17:58 UTC, cgalvan approved these changes

2022-11-23 16:26 UTC, allisaurus commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/session-management/_index.md
> +A game session is the defined as the time your server process is available to host players. Typically, a session ends when a game specific condition is met, which may include all players left the ses
```suggestion
A game session is defined as the time your server process is available to host players. Typically, a session ends when a game specific condition is met, which may include all players have left the session, player(s) reach a win condition, or a time period has expired. 
```

2022-11-23 16:27 UTC, allisaurus commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/flexmatch/_index.md
> +[GameLift FlexMatch](https://docs.aws.amazon.com/gamelift/latest/flexmatchguide/match-intro.html) provides matchmaking features to find and group players together for online multiplayer games.
```suggestion
[Amazon GameLift FlexMatch](https://docs.aws.amazon.com/gamelift/latest/flexmatchguide/match-intro.html) provides matchmaking features to find and group players together for online multiplayer games.
```

2022-11-23 16:28 UTC, allisaurus commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/_index.md
> +- [FlexMatch](https://docs.aws.amazon.com/gamelift/latest/flexmatchguide/match-intro.html) - to understand how matchmaking and GameLift works.
```suggestion
- [FlexMatch](https://docs.aws.amazon.com/gamelift/latest/flexmatchguide/match-intro.html) - to understand how matchmaking and Amazon GameLift works.
```

2022-11-23 22:07 UTC, allisaurus approved these changes

2022-11-28 17:04 UTC, willihay requested changes

2022-11-29 16:20 UTC, willihay approved these changes

2022-11-29 17:36 UTC, merged