Terrain detail and macro materials tutorial
o3de/o3de.org pull request #2129
Opened 2022-11-29 18:26 UTC by cgalvan

## Change summary

New tutorial to explain techniques for using macro materials and detail mapping together.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

2022-12-06 19:13 UTC, chanmosq commented
Requesting a technical review from @sig-content-reviewers as well!

2022-12-08 23:02 UTC, micronAMZN requested changes
Nice work. I added a bunch of suggestions for style guidance and table formatting.

2022-12-09 15:44 UTC, micronAMZN commented
On hold for image updates.

2023-01-18 19:03 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +This tutorial explains how to use frequency separation to create textures for terrain in **Open 3D Engine (O3DE)**. This is an image technique which is often used in retouching photos. However, it ca
I'll re-work this intro, thanks!

2023-01-18 19:08 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +Here is the original image:
Sounds good!

2023-01-18 20:19 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +| Original Low Pass (1024 x 1024 pixels) | Downsampled (64 x 64 pixels) | Interpolated (Bilinear) | Interpolated + Original High Pass (Reconstructed blend) | Difference (Original minus Reconstructed
Thanks!

2023-01-18 20:23 UTC, cgalvan commented
I'm in the process of incorporating Mike's feedback, plus new images and some updated sections from Jonny.

2023-01-18 20:26 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +If you are working with tiling images, you will want to use the following steps in order to make sure that both the low pass and high pass will continue to properly tile after the frequency splitting
I like this change, added!

2023-01-18 20:26 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +  * Width/Height: 33.33%, or the <original image size> in pixels
Thanks this looks great!

2023-01-18 20:29 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +Now, when the low pass (blur) is calculated, the pixel information wraps. Then, when it's subtracted and cropped both the low pass and the high pass will still tile properly.
Thanks this is more informative!

2023-01-18 22:16 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +As you can see in the screenshot, we've restored the original image fidelity by properly blending the low + high pass frequencies back together.
Good idea, incorporated!

2023-01-18 22:16 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +We will downsample the low pass to a much smaller image, then reconstruct the image from two maps of different resolutions. Theoretically, we will loose some information which may decrease aspects li
Yeah this sounds better, updated!

2023-01-18 22:17 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +At this level of downsampling, we are starting to see a perceptible difference in integrity, and the quality is arguably diminished. However, the fidelity is still good enough to be useful for our te
Agreed, and yes good catch I think it should be "detail" so I'll change that as well.

2023-01-18 22:18 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +We can use the small downsampled low pass image in texturing for our Macro material. There are a several options for this use case:
Done!

2023-01-18 22:18 UTC, cgalvan commented on content/docs/learning-guide/tutorials/environments/understanding-frequency-separation.md
> +Then with the proper blending and syncing the repeat, we can augment this with the the high pass detail texture and result in something similar to our original image up close.
Done!

2023-01-19 22:49 UTC, HogJonny-AMZN approved these changes

2023-01-19 22:51 UTC, mbalfour-amzn approved these changes

2023-01-20 20:38 UTC, micronAMZN approved these changes

2023-01-20 20:38 UTC, merged