add subtle issue description
o3de/o3de.org pull request #2164
Opened 2022-12-09 12:54 UTC by siliconvoodoo

describe about how class field access before its declaration can cause an internal issue

Signed-off-by: siliconvoodoo <vivien.oddou@siliconstudio.co.jp>

## Change summary

Documentation addition of subtle potential problem with class

2022-12-09 18:45 UTC, micronAMZN requested changes
A couple of minor style suggestions. Thanks for your contribution.

2022-12-09 18:45 UTC, micronAMZN commented on content/docs/atom-guide/dev-guide/shaders/azsl/_index.md
> +## class method, late declaration member access
Suggest sentence casing for headers.

```suggestion
## Class method, late declaration member access
```

2022-12-09 18:45 UTC, micronAMZN commented on content/docs/atom-guide/dev-guide/shaders/azsl/_index.md
> +> source.azsl(5,3) : warning: undeclared sub-symbol in idexpression: a
Suggest putting this is a shell code block.

````suggestion
```shell
source.azsl(5,3) : warning: undeclared sub-symbol in idexpression: a
```
````

2022-12-14 23:06 UTC, FiniteStateGit approved these changes

2022-12-15 16:19 UTC, micronAMZN approved these changes

2022-12-15 16:19 UTC, merged