Update generating_android_project_windows.md
o3de/o3de.org pull request #2314
Opened 2023-03-16 00:19 UTC by bhaskar1001101

## Change summary

Closes #1178
Added backticks to **8.** and **9.** in the **Prerequisites** section on [this page](https://www.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/)

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

2023-03-16 15:01 UTC, willihay requested changes

2023-03-16 20:38 UTC, chanmosq commented
@bhaskar1001101 Can you retarget this PR to development instead of main? You may need to make sure you're branch is up-to-date with main instead of development

2023-03-17 11:29 UTC, bhaskar1001101 commented
@chanmosq I have retargeted the PR to the development branch. My branch is up-to-date with the main branch.

2023-03-17 17:46 UTC, chanmosq commented
@bhaskar1001101 Because the changes are minor, I'll switch it back to `main`, and separately sync it with `development`. This one can be good to merge. Thanks for the fix!

2023-03-17 17:47 UTC, chanmosq approved these changes

2023-03-17 18:10 UTC, FiniteStateGit approved these changes

2023-03-17 18:25 UTC, willihay commented on content/docs/user-guide/platforms/android/generating_android_project_windows.md
> +9.  [Atom Sample Viewer](https://github.com/o3de/o3de-atom-sampleviewer.git) has been cloned locally on the system (to `D:\\github\\o3de-atom-sampleviewer`)
Whoops, just realized the double backslashes are no longer needed, now that you've got the back quotes in there.
```suggestion
8.  [O3DE](https://github.com/o3de/o3de.git) has been cloned locally on the system (to `D:\github\o3de`)
9.  [Atom Sample Viewer](https://github.com/o3de/o3de-atom-sampleviewer.git) has been cloned locally on the system (to `D:\github\o3de-atom-sampleviewer`)
```

2023-03-17 18:27 UTC, willihay approved these changes

2023-03-17 18:28 UTC, merged