Add server targets example links to AWSGameLift gem setup
o3de/o3de.org pull request #2323
Opened 2023-03-24 21:19 UTC by allisaurus

## Change summary

Adds additional explanation and links to example projects where gem setup directs users to update their project's "server target", which may not exist if users haven't started with a multiplayer template.

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

2023-03-24 21:35 UTC, lmbr-pip approved these changes

2023-03-24 21:38 UTC, AMZN-Gene approved these changes

2023-03-27 14:57 UTC, willihay requested changes

2023-03-27 14:57 UTC, willihay commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/gem-setup.md
> +1. **(Required)** You must include **Gem::AWSGameLift.Server.Static** as one of the **BUILD_DEPENDENCIES** for your project's server target. For an example of a networked project configured with dist
For added convenience, you could link directly to the `CMakeLists.txt` files that have the examples you describe:
```suggestion
1. **(Required)** You must include **Gem::AWSGameLift.Server.Static** as one of the **BUILD_DEPENDENCIES** for your project's server target. For an example of a networked project configured with distinct server and client targets, see the [O3DE Multiplayer project template](https://github.com/o3de/o3de-extras/blob/development/Templates/Multiplayer/Template/Gem/Code/CMakeLists.txt) or the [O3DE Multiplayer Sample project](https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Code/CMakeLists.txt).
```

2023-03-28 17:21 UTC, merged