Lyn 17890 tiaf dev docs
o3de/o3de.org pull request #2338
Opened 2023-04-02 20:11 UTC by jonawals

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2023-04-03 21:27 UTC, chanmosq commented
`_index.md` files are reserved as landing pages for a directory section, and directories are only needed to define a section that contains a collection of docs. Therefore, you should restructure and rename the files to match the following: 
```
- engine-dev/tools/tiaf/
  - _index.md
  - architectural-overview/
    - _index.md
    - ar-integration.md
    - runtime-frontend/
      - _index.md
      - frontend.md (if only one file, don't need a directory)
      - runtime/
        - _index.md
        - artifact.md
        - build-target.md
        - dependency.md
        - process.md
        - target.md
        - test-engine.md
        - test-runner.md
  - extending-tiaf.md (if only one file, don't need a directory)
  - maintaining.md (if only one file, don't need a directory)
```

2023-04-03 22:00 UTC, chanmosq requested changes

2023-04-04 15:10 UTC, closed without merging

2023-04-06 10:38 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/build-target/_index.md
> +The build targets are a higher level abstraction of the [targets]() that treat the individual test and produciton target types as a single, generic build target. Each build target contains a [variant
Out of date 👍

2023-04-06 10:39 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/_index.md
> +description: Information about the TIAF Runtime and Front End.
Fixed 👍

2023-04-06 10:40 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/_index.md
> +The architecture of the TIAF is broadly broken down into two areas: the [Automated Review Integration](./ar-integration), which concerns the integration of the TIAF runtime binaries into O3DE's autom
Fixed 👍

2023-04-06 10:41 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/_index.md
> +Below is a simplified diagram of the ssubsystems that make up the runtime and front end, and how they interact with one another:
Fixed 👍

2023-04-06 10:43 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/_index.md
> +The runtime and front end work together to present a unified interface to the user for selecting, prioritizing and running tests before presenting a report of the test results to the user. The runtim
Fixed 👍

2023-04-06 10:43 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/dependency/_index.md
> +description: Information about the TIAF dynamic dependencies.
Out of date 👍

2023-04-06 10:44 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/process/_index.md
> +description: Information about the TIAF process invocation and sheduling.
Out of date 👍

2023-04-06 10:46 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/maintaining-tiaf/_index.md
> +description: Information as to how to maintain the TIAF.
Fixed 👍

2023-04-06 10:49 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/dependency/_index.md
> +## Test Selector & Prioritizor
I agree with your suggested naming but it's actually the name of a class (`TestSelectorAndPrioritizor`). I will use that name (with the code markdown) to make it clearer it's a class name 👍

2023-04-06 10:49 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/target/_index.md
> +description: Information about the TIAF targets.
Out of date 👍

2023-04-06 10:50 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/test-engine/_index.md
> +description: Information about the TIAF test engine.
Out of date 👍

2023-04-06 10:50 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/runtime-frontend/runtime/_index.md
> +description: Information about the TIAF Runtime.
Out of date 👍

2023-04-06 11:06 UTC, jonawals commented on content/docs/engine-dev/tools/tiaf/architectural-overview/_index.md
> +| [Runtime & Front End](./runtime-frontend) | Learn about the architecture of the TIAF runtime and front end.|
Fixed 👍

2023-04-06 11:06 UTC, jonawals commented on content/docs/engine-dev/tools/_index.md
> +| [Test Impact Analysis Framework](./tiaf) | Learn about the internals of the **Test Impact Analysis Framework**, including an overview of the major classes and data structures that work together to
Fixed +1

2023-04-06 14:40 UTC, jonawals commented
Structure suggestion from https://github.com/o3de/o3de.org/pull/2338#issuecomment-1495004886 has been fixed 👍