Update ragdoll.md
o3de/o3de.org pull request #2558
Opened 2024-05-14 23:26 UTC by YufeiJ1ao

Resolve broken link for #2486 
Change the link for [Creating and Simulating a PhysX Ragdoll](https://docs.o3de.org/docs/user-guide/visualization/animation/animation-editor/creating-and-simulating-physx-ragdoll/) from
 /docs/user-guide/visualization/animation/animation-editor/creating-and-simulating-physx-ragdoll/ 
to 
[/docs/user-guide/visualization/animation/animation-editor/ragdoll/ragdoll-simulating-in-editor.md](https://www.docs.o3de.org/docs/user-guide/visualization/animation/animation-editor/ragdoll/ragdoll-simulating-in-editor/)

## Change summary

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

2024-06-17 16:23 UTC, ShaunaGordon requested changes

2024-06-17 16:23 UTC, ShaunaGordon commented on content/docs/user-guide/components/reference/physx/ragdoll.md
> +1. Use the **Animation Editor** to create and control the physical representation of the ragdoll. For more information, see [Creating and Simulating a PhysX Ragdoll](/docs/user-guide/visualization/an
```suggestion
1. Use the **Animation Editor** to create and control the physical representation of the ragdoll. For more information, see [Creating and Simulating a PhysX Ragdoll](/docs/user-guide/visualization/animation/animation-editor/ragdoll/ragdoll-simulating-in-editor).
```

Links aren't to the markdown files, themselves, but to the generated URL. In this case, it's the same path, minus the extension.

2026-04-07 15:31 UTC, ShaunaGordon commented
No activity recently and no response from the author regarding updating and changing the base branch. Feel free to re-open or submit a new PR with the necessary updates.

2026-04-07 15:31 UTC, closed without merging

2026-04-22 01:29 UTC, JT-SCB-GameDesign commented
Thanks, ya, I plan on looking into this as soon as I get up to speed with my dev environment since I've worked with ragdoll physics in the past.