Update Kythera setup guide to use the project centric workflow
o3de/o3de.org pull request #767
Opened 2021-07-27 10:33 UTC by fabioanderegg

2021-07-29 00:16 UTC, sptramer requested changes
Changes requested due to style issues throughout.

Please review the [O3DE Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/) before making future pull requests or changes.

2021-07-29 00:16 UTC, sptramer commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +1. Select the KytheraAIDemo folder in the unpacked zip folder
```suggestion
1. Select the `KytheraAIDemo` folder in the unpacked zip folder.
```

2021-07-29 00:16 UTC, sptramer commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +    1. Build the target `Kythera.Editor`, which is in one of the subdirectories matching the full filesystem path to the Gem
See above.

```suggestion
1. Open the project's Visual Studio solution (`<project directory>/build/windows_vs2019/<project name>.sln`).
1. Switch the build type from `debug` to `profile`.
1. Build the target `Kythera.Editor`, which is in one of the subdirectories matching the full filesystem path to the Gem.
```

2021-07-29 00:16 UTC, sptramer commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +1. In the project menu, click `Edit Project Settings` and then the `Configure Gems` button on the top right corner
```suggestion
1. Open the O3DE Project Manager (`o3de.exe`).
1. In the project menu, click `Edit Project Settings` and then the `Configure Gems` button on the top right corner.
```

2021-07-29 08:37 UTC, fabioanderegg commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +    1. Build the target `Kythera.Editor`, which is in one of the subdirectories matching the full filesystem path to the Gem
The issue has been fixed yesterday in the development branch. I'll check with the team if we can get the fix into the stabilization branch and completely remove the section (maybe with a note that users need a recent version of the engine).

2021-08-02 14:10 UTC, fabioanderegg commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +1. Unpack the zip file to some folder
The name of the zip file changes with every release, but I think I can fix the sentence in another way.

2021-08-02 14:10 UTC, fabioanderegg commented on content/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup.md
> +    1. Build the target `Kythera.Editor`, which is in one of the subdirectories matching the full filesystem path to the Gem
Issue has been merged in both development and stabilization, so I will remove this section.

2021-08-02 14:57 UTC, fabioanderegg commented
Still struggling with the inline image. @sptramer your suggested change makes the list count from 1 again, and the image is not indented correctly.

I tried all kinds of stuff:
```
1. In the project menu, select **Build**.

    ![Project Menu Build](/images/user-guide/gems/kythera-ai/project-manager-project-menu-build.png)

1. Back in the O3DE launcher, click **Open Editor**.
```
4 spaces + 2 newlines: This pulls the list apart (just as it does here: http://localhost:1313/docs/user-guide/project-config/add-remove-gems/)

Other stuff like adding a newline after the image starts the list again.

Any ideas?

2021-08-02 16:38 UTC, sptramer commented
LGTM, and the image does render correctly in the staging site as indented/inline with the list.

2021-08-02 16:38 UTC, merged