Fix links in atom guide.
o3de/o3de.org pull request #775
Opened 2021-08-03 01:22 UTC by sptramer

This should resolve all bad links in the atom guide except for a few missing API references (which may have been removed from source?) and Atom components which don't have documentation available yet.

2021-08-04 19:50 UTC, chanmosq requested changes
Fix a few broken links.

2021-08-04 19:50 UTC, chanmosq commented on content/docs/atom-guide/features/_index.md
> +*Related to: [Mesh Feature Processor API](/docs/api/gems/Atom/class_a_z_1_1_render_1_1_mesh_feature_processor.html), [O3DE Mesh Component](/docs/user-guide/components/reference/atom/mesh), [Skinned M
We don't have a "Skinned Mesh Component". Rather, skinned meshes are applied to Actors. The Actor component documentation is currently out-of-date, so I think that linking to the Actor docs would be unnecessary at this time. 

```suggestion
*Related to: [Mesh Feature Processor API](/docs/api/gems/Atom/class_a_z_1_1_render_1_1_mesh_feature_processor.html), [O3DE Mesh Component](/docs/user-guide/components/reference/atom/mesh), [Skinned Mesh Feature Processer API](/docs/api/gems/Atom/class_a_z_1_1_render_1_1_skinned_mesh_feature_processor_interface.html)*  
```

2021-08-04 19:50 UTC, chanmosq commented on content/docs/atom-guide/features/_index.md
> +*Related to: [Post Process Feature Processor API](/docs/api/gems/Atom/class_a_z_1_1_render_1_1_post_process_feature_processor_interface.html), [O3DE Post Process Components](/docs/user-guide/componen
The PostFX components encompass multiple different components. 
```suggestion
*Related to: [Post Process Feature Processor API](/docs/api/gems/Atom/class_a_z_1_1_render_1_1_post_process_feature_processor_interface.html), O3DE PostFX components ([Gradient Weight](/docs/user-guide/components/reference/atom/postfx-gradient-weight-modifier/), [PostFX Layer](/docs/user-guide/components/reference/atom/postfx-layer/), [PostFX Shape Weight Modifier](/docs/user-guide/components/reference/atom/postfx-shape-weight-modifier/), [Radius Weight Modifier](/docs/user-guide/components/reference/atom/radius-weight-modifier/)).* 
```

2021-08-04 19:50 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/decal.md
> +[Atom Gem](/docs/atom-guide)
```suggestion
[Atom Gem](/docs/user-guide/gems/reference/rendering/atom/atom/)
```

2021-08-04 19:50 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/diffuse-gi.md
> +[Atom Gem](/docs/atom-guide)
```suggestion
[Atom Gem](/docs/user-guide/gems/reference/rendering/atom/atom/)
```

2021-08-04 21:36 UTC, willihay requested changes

2021-08-04 21:36 UTC, willihay commented on content/docs/user-guide/components/reference/atom/light.md
> +| Point (sphere) | [Sphere Shape](/docs/user-guide/components\reference\shape\sphere-shape/) |
```suggestion
| Point (sphere) | [Sphere Shape](/docs/user-guide/components/reference/shape/sphere-shape/) | 
```

2021-08-11 20:15 UTC, chanmosq approved these changes

2021-08-11 20:16 UTC, merged