Added properties info to Reflection Probe component.
o3de/o3de.org pull request #783
Opened 2021-08-03 22:04 UTC by chanmosq

2021-08-04 05:46 UTC, dmcdiarmid-ly approved these changes

2021-08-04 14:55 UTC, micronAMZN requested changes

2021-08-04 14:55 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/reflection-probe.md
>  {{< preview-new >}}
New component, new topic, don't think we need the preview banner for this.

```suggestion
```

2021-08-04 14:55 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/reflection-probe.md
>  ## Provider ##
```suggestion
 ## Provider
```

2021-08-06 01:24 UTC, micronAMZN approved these changes

2021-08-06 01:24 UTC, merged