Diffuse Probe Grid component docs
o3de/o3de.org pull request #789
Opened 2021-08-05 21:29 UTC by chanmosq

Updated the Diffuse Probe Grid component's reference page.

2021-08-06 15:11 UTC, micronAMZN requested changes

2021-08-06 15:11 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +The **Diffuse Probe Grid component** creates a volume of light probes that provide diffuse global illumination (GI) within the specified area. Each probe in the volume uses real-time ray tracing to c
```suggestion
The **Diffuse Probe Grid** component creates a volume of light probes that provide diffuse global illumination (GI) within the specified area. Each probe in the volume uses real-time ray tracing to capture the *irradiance*, or surrounding diffuse light environment. Real-time ray tracing casts several hundred rays in different directions around each probe. The probe stores lighting information at each point of intersection between the ray and the mesh. Then, it creates an irradiance texture out of the ray traced data and applies the texture to each mesh.
```

2021-08-06 15:11 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +Probe spacing is the distance between probes (in meters) along each axis within the volume. Less spacing results in more probes, which increases the fidelity of the GI at the expense of performance a
```suggestion
 Probe spacing is the distance between probes (in meters) along each axis within the volume. Less spacing results in more probes, which increases the fidelity of the GI at the expense of performance and memory. The maximum extents of the space depends on the **Box Shape** component's dimension.
```

2021-08-16 19:27 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +| **Z-Axis** | The amount of space between probes along the z-axis. The space must be within the Box Shape component's dimension along the z-axis. | `0.0` to the Box Shape component's `Dimensions`-`Z
After reviewing this, you're right the default value is 2.0 meters. I believe what I was observing may have been the probe spacing values updating when I update the mesh.

2021-08-16 19:29 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +The **Diffuse Probe Grid** component creates a volume of light probes that provide diffuse global illumination (GI) within the specified area. Each probe in the volume uses real-time ray tracing to c
I think mesh may refer to the surrounding geometry? Or just the geometry within the volume. 

@dmcdiarmid-ly Can you specify?

2021-08-17 01:24 UTC, chanmosq commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +The **Diffuse Probe Grid** component creates a volume of light probes that provide diffuse global illumination (GI) within the specified area. Each probe in the volume uses real-time ray tracing to c
I believe the meshes that the rays intersect with refer to all of the geometry in the level that are in the direction of the ray. 

Hopefully this is more clear. I updated the sentence to: 
> At each point of intersection between the ray and the surrounding geometry, the probe stores lighting information.

2021-08-17 15:41 UTC, willihay approved these changes

2021-08-18 16:11 UTC, micronAMZN approved these changes

2021-08-18 16:18 UTC, merged