User Guide banner fix 1: Includes main _index, /appendix, and /assets…
o3de/o3de.org pull request #807
Opened 2021-08-12 22:00 UTC by micronAMZN

…. Removed preview banners, set zero length topics to draft, commented out links to zero length topics in this PR, other minor fixes such as removing H2s that duplicate topic title.

Signed-off-by: Mike Cronin <mikecro@amazon.com>

2021-08-13 19:15 UTC, willihay requested changes
Let's get rid of the `date` front matter too. It messes with the order of the ToC. Can you check _all_ the topics in the appendix?

2021-08-13 19:15 UTC, willihay commented on content/docs/user-guide/appendix/command-line-tools.md
>  date: 2021-03-02T00:23:56-05:00
```suggestion
```

2021-08-13 19:15 UTC, willihay commented on content/docs/user-guide/appendix/cvars/_index.md
>  date: 2021-03-04
```suggestion
```

2021-08-13 19:15 UTC, willihay commented on content/docs/user-guide/appendix/cvars/debugging.md
>  title: Debugging Issues
```suggestion
title: Debug CVARs
```

2021-08-13 19:15 UTC, willihay commented on content/docs/user-guide/appendix/file-formats.md
>  date: 2021-03-02T00:23:56-05:00
```suggestion
```

2021-08-13 19:15 UTC, willihay commented on content/docs/user-guide/assets/fbx-settings/import/_index.md
>  date: 2021-03-04
```suggestion
```

2021-08-17 21:17 UTC, chanmosq approved these changes

2021-08-18 16:22 UTC, willihay approved these changes

2021-08-18 16:22 UTC, merged