Update of submit-a-pr.md for DCO
o3de/o3de.org pull request #827
Opened 2021-08-18 22:51 UTC by spotz

Updated instructions with workaround for DCO failure. New PR for https://github.com/o3de/o3de.org/pull/821 which was closed.

Signed-off-by: Amy Marrich (spotz) <amy@demarco.com>

2021-08-19 18:32 UTC, spotz commented
@willihay @micronAMZN - the older PR was closed so created a new one. Tagging you both as I wasn't able to add reviewers.

2021-08-20 20:51 UTC, micronAMZN requested changes

2021-08-20 20:51 UTC, micronAMZN commented on content/docs/contributing/to-docs/submit-a-pr.md
> +If you used the web UI to make your commit vs the commandline, your PR may fail the DCO check and you will need to add a `Signed-off-by:` line to your commit message. For GitHub accounts made prior t
```suggestion
If you use the GitHub web UI to make your commit, you must add a `Signed-off-by:` line to your commit message or the DCO check will fail. For GitHub accounts created prior to July 18, 2017, use `username@users.noreply.github.com` as the email address. For accounts created after that date, use your GitHub-provided no-reply email address. The new no-reply email address is a seven-digit ID number and your username in the form of `ID+username@users.noreply.github.com` that can be found in the email tab of your GitHub account settings. For more information about setting your commit email address, refer to the [Setting your commit email address instructions](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address).
```

2021-08-20 21:35 UTC, spotz reviewed
Thanks!

2021-08-20 21:58 UTC, micronAMZN commented
> 
> 
> Thanks!

This commit failed the DCO :) Could you amend the last commit with a sign-off?

2021-08-20 22:55 UTC, spotz commented
This got stuck ironically in a DCO loop so closing. Will work on getting documentation so folks don't get in a loop:)

2021-08-20 22:55 UTC, closed without merging