Update the Diffuse Probe Grid component
o3de/o3de.org pull request #828
Opened 2021-08-19 00:43 UTC by chanmosq

Added a note about Diffuse Probe Grid component - ray length is limited to 20 meters.

2021-08-19 01:11 UTC, micronAMZN requested changes

2021-08-19 01:11 UTC, micronAMZN commented on content/docs/user-guide/components/reference/atom/diffuse-probe-grid.md
> +- The length of the rays that're casted from the probe is limited to 20 meters.
Feels like this is a pretty important piece of info that should be incorporated into the opening paragraph, and this section can be removed.

"...casts several hundred rays in different directions around each probe. Each ray has a maximum length of 20 meters. ..."

2021-08-24 14:37 UTC, micronAMZN approved these changes

2021-08-24 17:33 UTC, dmcdiarmid-ly approved these changes

2021-08-24 18:43 UTC, merged