Add TOC navigation to environment subfolder Issue#854
o3de/o3de.org pull request #866
Opened 2021-09-02 17:14 UTC by FiniteStateGit

Fixes [ISSUE][DOCS] Table of contents not enabled for pages in Vegetation Gem https://github.com/o3de/o3de.org/issues/854

Created new __index.md for the Environment subfolder, assigned weights for TOC and cleaned up frontmatter of directory.

2021-09-03 22:44 UTC, sptramer requested changes
Some minor copy changes requested. Thanks for your contribution!

2021-09-03 22:44 UTC, sptramer commented on content/docs/user-guide/gems/reference/environment/_index.md
> +The [Landscape Canvas Gem](./landscape-canvas.md) provides the **Landscape Canvas** editor; a node-based graph tool for authoring workflows to populate landscape with dynamic vegetation.
```suggestion
The [Landscape Canvas Gem](./landscape-canvas) provides the **Landscape Canvas** editor, a node-based graph tool for authoring workflows to populate landscape with dynamic vegetation.
```

2021-09-03 22:44 UTC, sptramer commented on content/docs/user-guide/gems/reference/environment/_index.md
> +The [Vegetation Assets Gem](./vegetation-gem-assets.md) provides vegetation models, textures, and other assets and samples for use with the Vegetation Gem and **Landscape Canvas**.
```suggestion
The [Vegetation Assets Gem](./vegetation-gem-assets) provides vegetation models, textures, and other assets and samples for use with the Vegetation Gem and **Landscape Canvas**.
```

2021-09-03 22:44 UTC, sptramer commented on content/docs/user-guide/gems/reference/environment/_index.md
> +The [Surface Data Gem](./surface-data.md) enables surfaces such as terrain or meshes to emit signals or tags, that communicate its surface type. These signals and tags have various uses, such as crea
```suggestion
The [Surface Data Gem](./surface-data) enables surfaces such as terrain or meshes to emit signals or tags, that communicate its surface type. These signals and tags have various uses, such as creating inclusion and exclusion areas for vegetation growth.
```

2021-09-06 21:09 UTC, sptramer approved these changes

2021-09-07 18:21 UTC, micronAMZN approved these changes

2021-09-07 18:21 UTC, merged