[SPEC-8103] Update GameLift server instructions for new exposed API
o3de/o3de.org pull request #869
Opened 2021-09-04 03:12 UTC by onecent1101

Signed-off-by: Liu <liug@amazon.com>

2021-09-09 16:46 UTC, junbo75 reviewed
General question: Did you mention about starting the GameLiftLocal before the launcher if customers want to test it locally in this document?

2021-09-09 16:46 UTC, junbo75 commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +// For example, make asynchronous call to search active game sessions on specific fleet and get response from notification
nit: "on a specific fleet" ?

2021-09-09 16:46 UTC, junbo75 commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +// For example, make synchronous call to join specific session
Nit: "join a specific session" ？

2021-09-09 16:46 UTC, junbo75 commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +// For example, make asynchronous call to join specific session and get response from notification
Nit: "join a specific session" ？

2021-09-09 16:59 UTC, lmbr-pip reviewed
LG overall.

2021-09-09 16:59 UTC, lmbr-pip commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +// For example, make synchronous call to leave current session
nit: "leave the current session"

2021-09-09 16:59 UTC, lmbr-pip commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +// For example, make asynchronous call to leave current session and get notification after process is complete
nit: leave the current session and get a notification after the process is complete. 

I would also be wary of "process" here as GameLift has definition of process. Maybe "and get a notification, once the leaving the session is completed"?

2021-09-09 16:59 UTC, lmbr-pip commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +Put this call in a proper place on your server side, like server system component activate step, and call it after you connect your project to `AzFramework::SessionNotificationBus`.
nit: "proper place" seems to indicate there is a definite place. Maybe "Call process ready once your have completed any relevant initialization. One recommended sport is in the [ServerSystemCompontent]'s activate step, after connecting to the `AzFramework::SessionNotificationBus`

2021-09-09 16:59 UTC, lmbr-pip commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +Once your session is created, it broadcasts the following notifications through `AzFramework::SessionNotificationBus` on server side. You can program how your session responds to these notifications.
nit: "Once the game session is created, the a notification is broadcast through... You can then listen to the notification to {insert example of what customer should do here}"

2021-09-09 16:59 UTC, lmbr-pip commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/gem-setup.md
> +2. **(Required)** In order to make sure Amazon GameLift Server SDK get initiated correctly before your project server starts, you must mark `AWSGameLiftServerService` as required for your project ser
"To ensure that the Amazon GameLift Server SDK gets intialized correctly...."

2021-09-09 18:04 UTC, onecent1101 commented
> General question: Did you mention about starting the GameLiftLocal before the launcher if customers want to test it locally in this document?

It is in local testing section https://docs.o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/local-testing/

2021-09-10 16:27 UTC, junbo75 approved these changes

2021-09-13 17:36 UTC, lmbr-pip approved these changes
LG

2021-09-15 21:31 UTC, willihay requested changes

2021-09-15 21:31 UTC, willihay commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +Call process ready once your have completed any relevant initialization. One recommended place is in `YourProjectServerSystemComponent` activate step, after connecting to `AzFramework::SessionNotific
Update to improve flow and use active voice:
```suggestion
To send a notification that your server process is ready, complete any relevant initialization and then use `AWSGameLiftServerRequestBus::Events::NotifyGameLiftProcessReady()`. We recommend placing the call after connecting to `AzFramework::SessionNotificationBus`, in the `YourProjectServerSystemComponent` activation step.

Example call:
```

2021-09-15 21:31 UTC, willihay commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +Once the game session is created, following notifications are broadcast through `AzFramework::SessionNotificationBus`. You can program how your session responds to these notifications.
```suggestion
After the game session has been created, notifications are broadcast through `AzFramework::SessionNotificationBus`. You can program how your session responds to these notifications.
```

2021-09-15 21:31 UTC, willihay commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/gem-setup.md
> +2. **(Required)** To ensure that the Amazon GameLift Server SDK gets initialized correctly, you must mark `AWSGameLiftServerService` as required for your project server system component.
```suggestion
2. **(Required)** To ensure that the Amazon GameLift Server SDK gets initialized correctly, you must indicate that the `AWSGameLiftServerService` is required for your project server system component.
```

2021-09-15 22:08 UTC, willihay requested changes

2021-09-15 22:08 UTC, willihay commented on content/docs/user-guide/gems/reference/aws/aws-gamelift/cpp-api.md
> +We recommended placing the call after connecting to `AzFramework::SessionNotificationBus` in the `YourProjectServerSystemComponent` activate step.
```suggestion
We recommend placing the call after connecting to `AzFramework::SessionNotificationBus` in the `YourProjectServerSystemComponent` activate step.
```

2021-09-15 22:20 UTC, willihay approved these changes

2021-09-15 22:20 UTC, merged