Formatting fixes and cleanup
o3de/o3de.org pull request #870
Opened 2021-09-04 04:50 UTC by FiniteStateGit

Fixes Issues: https://github.com/o3de/o3de.org/issues/190 https://github.com/o3de/o3de.org/issues/205 https://github.com/o3de/o3de.org/issues/206 https://github.com/o3de/o3de.org/issues/207 https://github.com/o3de/o3de.org/issues/208 https://github.com/o3de/o3de.org/issues/273 https://github.com/o3de/o3de.org/issues/290

Also added note shortcodes, removed several links to non-existent pages, fixed anchor.

2021-09-06 21:21 UTC, sptramer requested changes
Formatting change fixes. Thanks for your contribution!

2021-09-06 21:21 UTC, sptramer commented on content/docs/user-guide/components/reference/physx/rigid-body-physics.md
> +    ![\[Animated example of a dynamic entity falling to the terrain and bouncing around.\]](/images/user-guide/shared/physx-creating-dynamic-object-1.gif)
```suggestion
    ![Animated example of a dynamic entity falling to the terrain and bouncing around.](/images/user-guide/shared/physx-creating-dynamic-object-1.gif)
```

2021-09-06 21:21 UTC, sptramer commented on content/docs/user-guide/gems/reference/environment/vegetation/procedures/layer.md
> +1. Create an entity(/docs/userguide/creating-entity.md) and name it.
```suggestion
1. Create an entity and name it.
```

2021-09-06 21:21 UTC, sptramer commented on content/docs/user-guide/gems/reference/environment/vegetation/procedures/selection-random.md
> +## Creating a Gradient Entity {#create-gradient-entity}
Avoid the use of manually-defined anchors in headers; the autogenerated anchor here is named `creating-a-gradient-entity`.

```suggestion
## Creating a Gradient Entity
```

2021-09-07 15:56 UTC, micronAMZN approved these changes

2021-09-10 03:50 UTC, sptramer approved these changes

2021-09-10 03:50 UTC, merged