Fixed formatting user-guide/visualization/animation Issue#239
o3de/o3de.org pull request #872
Opened 2021-09-04 19:18 UTC by FiniteStateGit

Issue https://github.com/o3de/o3de.org/issues/239

2021-09-06 21:50 UTC, sptramer requested changes
Some minor changes requested. Thanks for your contribution!

2021-09-06 21:50 UTC, sptramer commented on content/docs/user-guide/visualization/animation/referencing-character-animation-editor-anim-graph.md
> +## Best Practices for Using Referenced Anim Graphs {#character-animation-editor-anim-graph-reference-best-practices}
```suggestion
## Best Practices for Using Referenced Anim Graphs
```

2021-09-06 21:50 UTC, sptramer commented on content/docs/user-guide/visualization/animation/set-up-a-simulated-object.md
> +    After you create an anim graph, you can preview the simulation. For now, keep the default values.
```suggestion
    {{< note >}}
After you create an anim graph, you can preview the simulation. For now, keep the default values.
{{< /note >}}
```

2021-09-07 15:49 UTC, micronAMZN approved these changes

2021-09-10 03:52 UTC, sptramer approved these changes

2021-09-10 03:52 UTC, merged