Add shortcodes to note, warning, caution and important callouts
o3de/o3de.org pull request #873
Opened 2021-09-04 22:39 UTC by FiniteStateGit

2021-09-07 15:39 UTC, micronAMZN approved these changes

2021-09-21 20:42 UTC, sptramer requested changes
Some minor fixes that look like bad automation or a mistype.

2021-09-21 20:42 UTC, sptramer commented on content/docs/user-guide/packaging/asset-bundler/list-operations.md
> +comparison operation](#asset-bundler-list-operations-delta), which includes a file entry in both sets if one of those files has been modified in the second set. Additionally, file pattern matching is
```suggestion
While the comparison operations use terms from set theory, they are not exactly the same as the actual set operations. This is particularly true of the [delta comparison operation](#asset-bundler-list-operations-delta), which includes a file entry in both sets if one of those files has been modified in the second set. Additionally, file pattern matching is not a set operation.
```

2021-09-21 20:42 UTC, sptramer commented on content/docs/user-guide/scripting/lua/debugging-tutorial.md
> +    ```F
```suggestion
    ```
```

2021-09-21 21:10 UTC, FiniteStateGit commented
Thanks for catching those mistypes.

2021-09-27 23:48 UTC, merged