Reorganized Learning Guide index pages and added Create a Level tutor…
o3de/o3de.org pull request #883
Opened 2021-09-09 22:22 UTC by micronAMZN

…ial.

Signed-off-by: Mike Cronin <mikecro@amazon.com>

2021-09-11 03:06 UTC, chanmosq requested changes

2021-09-11 03:06 UTC, chanmosq commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +In Open 3D Engine (O3DE), a *level* is a playable section of a project. Within a level, you create entities, instantiate prefabs, arrange lights and cameras, and implement scripted behaviors and inte
```suggestion
In **Open 3D Engine (O3DE)**, a *level* is a playable section of a project. Within a level, you create entities, instantiate prefabs, arrange lights and cameras, and implement scripted behaviors and interactivity. A level can be interpreted literally as a level of a game, however, levels are the basis for all O3DE projects. Non-gaming applications such as simulations require at least one level. A project can have a single level or many levels.

```

2021-09-11 03:06 UTC, chanmosq commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +| Global Sky | Contains a **Global Skylight (IBL)** component and a **HDRI Skybox** component. This entity provides image based lighting using a high dynamic range image and displays the image as a s
```suggestion
| Global Sky | Contains a **Global Skylight (IBL)** component and a **HDRI Skybox** component. This entity provides image-based lighting using a high dynamic range image and displays the image as a skybox. |

```

2021-09-11 03:06 UTC, chanmosq commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +| Camera | Contains a **Camera** component that provides a camera view a frustum to view the level, and a **Fly Camera Input** component that takes user input and moves the camera while in **Game** m
```suggestion
| Camera | Contains a **Camera** component that provides a camera view frustum to view the level, and a **Fly Camera Input** component that takes user input and moves the camera while in **Game** mode. |
```

2021-09-11 03:06 UTC, chanmosq commented on content/docs/learning-guide/tutorials/multiplayer/_index.md
> +This section contains step-by-step tutorials related to multiplayer in Open 3D Engine (O3DE).
```suggestion
This section contains step-by-step tutorials related to multiplayer in **Open 3D Engine (O3DE)**.
```

2021-09-14 20:20 UTC, willihay requested changes

2021-09-14 20:20 UTC, willihay commented on content/docs/learning-guide/tutorials/ai/_index.md
>  weight: 100
I suggest we remove the `weight` front matter from all tutorial _index.md files, to let them automatically sort in alphabetical order.
```suggestion
```

2021-09-14 20:20 UTC, willihay commented on content/docs/learning-guide/tutorials/environments/_index.md
> +weight: 100
```suggestion
```

2021-09-14 20:20 UTC, willihay commented on content/docs/learning-guide/tutorials/multiplayer/_index.md
>  menu_uuid: Multiplayer
```suggestion
```

2021-09-14 20:20 UTC, willihay commented on content/docs/learning-guide/tutorials/multiplayer/_index.md
>  menu_uuid: Multiplayer
No need for menu_uuid here, either.

2021-09-14 20:25 UTC, willihay commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +
Remove the empty line here. I just checked the preview and it's breaking the table.
```suggestion
```

2021-09-14 20:26 UTC, willihay commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +## Default Atom Environment contents
Did you mean 'Atom Default Environment contents'?
```suggestion
## Atom Default Environment contents

```

2021-09-14 21:18 UTC, willihay approved these changes

2021-09-17 00:18 UTC, chanmosq approved these changes

2021-09-22 00:17 UTC, JwGedit commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +Levels can be created from the **Welcome to O3DE** dialog box that appears when **O3DE Editor** is launched, or from the **File** menu within O3DE Editor.
```suggestion
You can create levels in the **Welcome to O3DE** dialog box that appears when **O3DE Editor** is launched, or from the **File** menu within O3DE Editor.

```

2021-09-22 00:22 UTC, JwGedit commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +1. Choose **Ok** to create the level.
```suggestion
1. Choose **OK** to create the level.

```

2021-09-22 00:23 UTC, JwGedit commented on content/docs/learning-guide/tutorials/environments/create-a-level.md
> +The new level is populated with some basic entities. In **Entity Outliner**, there is a root entity named **Atom Default Environment**. Click the arrow to the left of the default entity in Entity Out
```suggestion
The new level is populated with some basic entities. In **Entity Outliner**, there is a root entity named **Atom Default Environment**. Choose the arrow to the left of the default entity in **Entity Outliner** to expand the list of child entities.

```

2021-09-23 15:58 UTC, merged